/*
 * Bayley-4 Assessment Data
 * Organized by domain, subdomain, and age-based stages
 * Based on the Bayley Scales of Infant and Toddler Development, 4th Edition
 */

export type ScoringType = 'mastery' | 'frequency' | 'adaptive';

export interface AssessmentItem {
  id: string;
  number: number;
  text: string;
  scoringTip?: string;
  scoringCriteria?: string;
}

export interface AgeStage {
  label: string;
  ageRange: string;
  items: AssessmentItem[];
}

export interface Subdomain {
  id: string;
  name: string;
  abbreviation: string;
  itemCount: number;
  maxRawScore: number;
  scoringType: ScoringType;
  scoringLabels: { value: number; label: string }[];
  stages?: AgeStage[];
  items?: AssessmentItem[];
}

export interface Domain {
  id: string;
  name: string;
  abbreviation: string;
  color: string;
  colorClass: string;
  bgClass: string;
  borderClass: string;
  description: string;
  administrationType: 'direct' | 'caregiver';
  subdomains: Subdomain[];
  imageUrl?: string;
}

const masteryScoring = [
  { value: 2, label: 'Mastery' },
  { value: 1, label: 'Emerging' },
  { value: 0, label: 'Not Present' },
];

const frequencyScoring = [
  { value: 5, label: 'All of the time' },
  { value: 4, label: 'Most of the time' },
  { value: 3, label: 'Half of the time' },
  { value: 2, label: 'Some of the time' },
  { value: 1, label: 'None of the time' },
  { value: 0, label: "Can't tell" },
];

const adaptiveScoring = [
  { value: 2, label: 'Usually or often' },
  { value: 1, label: 'Sometimes' },
  { value: 0, label: 'Never' },
];

export const domains: Domain[] = [
  {
    id: 'cognitive',
    name: 'Cognitive',
    abbreviation: 'CG',
    color: '#0D7377',
    colorClass: 'text-[#0D7377]',
    bgClass: 'bg-[#0D7377]',
    borderClass: 'border-[#0D7377]',
    description: 'Assesses visual preference, attention, memory, sensorimotor exploration, concept formation, problem solving, and counting abilities.',
    administrationType: 'direct',
    imageUrl: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663309733831/cMqqYSsKCsL3dhdDqopNkg/domain-cognitive-epXt68XXkqehgCzgDHqvC9.webp',
    subdomains: [
      {
        id: 'cg',
        name: 'Cognitive',
        abbreviation: 'CG',
        itemCount: 81,
        maxRawScore: 162,
        scoringType: 'mastery',
        scoringLabels: masteryScoring,
        items: generateCognitiveItems(),
      },
    ],
  },
  {
    id: 'language',
    name: 'Language',
    abbreviation: 'LANG',
    color: '#B8860B',
    colorClass: 'text-[#B8860B]',
    bgClass: 'bg-[#B8860B]',
    borderClass: 'border-[#B8860B]',
    description: 'Evaluates receptive and expressive communication skills including preverbal behaviors, vocabulary development, and morpho-syntactic understanding.',
    administrationType: 'direct',
    imageUrl: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663309733831/cMqqYSsKCsL3dhdDqopNkg/domain-language-6tgULGZybaHyzrY6EMuYQi.webp',
    subdomains: [
      {
        id: 'rc',
        name: 'Receptive Communication',
        abbreviation: 'RC',
        itemCount: 42,
        maxRawScore: 84,
        scoringType: 'mastery',
        scoringLabels: masteryScoring,
        items: generateReceptiveItems(),
      },
      {
        id: 'ec',
        name: 'Expressive Communication',
        abbreviation: 'EC',
        itemCount: 37,
        maxRawScore: 74,
        scoringType: 'mastery',
        scoringLabels: masteryScoring,
        items: generateExpressiveItems(),
      },
    ],
  },
  {
    id: 'motor',
    name: 'Motor',
    abbreviation: 'MOT',
    color: '#2D6A4F',
    colorClass: 'text-[#2D6A4F]',
    bgClass: 'bg-[#2D6A4F]',
    borderClass: 'border-[#2D6A4F]',
    description: 'Measures fine motor skills (grasping, perceptual-motor integration) and gross motor skills (static positioning, dynamic movement, balance).',
    administrationType: 'direct',
    imageUrl: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663309733831/cMqqYSsKCsL3dhdDqopNkg/domain-motor-MCXpziCUkcwzHk8WDE5sXm.webp',
    subdomains: [
      {
        id: 'fm',
        name: 'Fine Motor',
        abbreviation: 'FM',
        itemCount: 46,
        maxRawScore: 92,
        scoringType: 'mastery',
        scoringLabels: masteryScoring,
        items: generateFineMotorItems(),
      },
      {
        id: 'gm',
        name: 'Gross Motor',
        abbreviation: 'GM',
        itemCount: 58,
        maxRawScore: 116,
        scoringType: 'mastery',
        scoringLabels: masteryScoring,
        items: generateGrossMotorItems(),
      },
    ],
  },
  {
    id: 'social-emotional',
    name: 'Social-Emotional',
    abbreviation: 'SOEM',
    color: '#C97B84',
    colorClass: 'text-[#C97B84]',
    bgClass: 'bg-[#C97B84]',
    borderClass: 'border-[#C97B84]',
    description: 'Measures social-emotional milestones through caregiver questionnaire, including sensory processing and emotional stages from self-regulation to logical bridges between emotions and ideas.',
    administrationType: 'caregiver',
    subdomains: [
      {
        id: 'sp',
        name: 'Sensory Processing',
        abbreviation: 'SP',
        itemCount: 8,
        maxRawScore: 40,
        scoringType: 'frequency',
        scoringLabels: frequencyScoring,
        items: [
          { id: 'sp-1', number: 1, text: 'Takes a calm and enjoyable interest in most sounds.' },
          { id: 'sp-2', number: 2, text: "You can easily get your child's attention without having to be very dramatic." },
          { id: 'sp-3', number: 3, text: 'Takes a calm and enjoyable interest in most sights, including colorful or bright things.' },
          { id: 'sp-4', number: 4, text: 'You can easily get your child to look at things without them being very bright or colorful.' },
          { id: 'sp-5', number: 5, text: 'Calmly enjoys touching or being touched by different things.' },
          { id: 'sp-6', number: 6, text: 'You can easily get your child to respond to your touch without having to touch your child firmly to get his/her attention.' },
          { id: 'sp-7', number: 7, text: 'Likes to be swung around, danced with while in your arms, or quickly lifted up in the air.' },
          { id: 'sp-8', number: 8, text: "You can easily get your child's attention by approaching him/her or moving him/her around slowly." },
        ],
      },
      {
        id: 'se',
        name: 'Social-Emotional',
        abbreviation: 'SE',
        itemCount: 27,
        maxRawScore: 135,
        scoringType: 'frequency',
        scoringLabels: frequencyScoring,
        stages: [
          {
            label: 'Stage 1',
            ageRange: '0–3 months',
            items: [
              { id: 'se-9', number: 9, text: 'You can help your child to calm down.' },
              { id: 'se-10', number: 10, text: 'Looks at interesting sights, such as your face or a toy.' },
              { id: 'se-11', number: 11, text: 'Looks at or turns toward interesting sounds.' },
            ],
          },
          {
            label: 'Stage 2',
            ageRange: '4–5 months',
            items: [
              { id: 'se-12', number: 12, text: 'Seems happy or pleased when he/she sees a favorite person (e.g., looks or smiles, makes sounds, or moves arms in a way that expresses joy or delight).' },
              { id: 'se-13', number: 13, text: 'Responds to people talking or playing with him/her by making sounds or faces (e.g., happy sounds or a curious or annoyed look).' },
            ],
          },
          {
            label: 'Stage 3',
            ageRange: '6–9 months',
            items: [
              { id: 'se-14', number: 14, text: 'Reaches for or points at things or makes distinct sounds to show you what he/she wants (e.g., reaches out to be picked up or points at a toy).' },
              { id: 'se-15', number: 15, text: 'Exchanges two or more smiles, other looks, sounds, or actions (e.g., reaching, giving, or taking) with a favorite person.' },
            ],
          },
          {
            label: 'Stage 4a',
            ageRange: '10–14 months',
            items: [
              { id: 'se-16', number: 16, text: 'Shows you that he/she understands your actions or gestures by making an appropriate gesture in return (e.g., makes a funny face back at you, looks at something you point to, stops doing something when you shake your head and use a firm voice to say "No!", or smiles and does more of something when you nod with a big smile and say "Yes!").' },
              { id: 'se-17', number: 17, text: 'Uses many consecutive actions in a back-and-forth way to show you what he/she wants or to have fun with you (e.g., smiles, reaches out for a hug, and when you hug, takes your hat, puts it on his/her head, and smiles proudly OR takes your hand, leads you to the refrigerator, tugs on the handle, and after you open it, points to something he/she likes, such as food, a bottle of juice, or milk).' },
            ],
          },
          {
            label: 'Stage 4b',
            ageRange: '15–18 months',
            items: [
              { id: 'se-18', number: 18, text: 'Copies or imitates many of your sounds, words, or actions while playing with you (e.g., if you make funny faces and sounds, he/she copies them).' },
              { id: 'se-19', number: 19, text: 'Searches for something he/she wants by looking or getting you to look for it.' },
              { id: 'se-20', number: 20, text: 'Shows you what he/she wants or needs by using a few actions in a row (e.g., leads you by the hand to open a door and then touches or bangs on the door).' },
              { id: 'se-21', number: 21, text: 'Uses words or tries to use words when people talk with or play with him/her.' },
            ],
          },
          {
            label: 'Stage 5a',
            ageRange: '19–24 months',
            items: [
              { id: 'se-22', number: 22, text: 'Copies or imitates familiar make-believe play (e.g., feeds or hugs a doll).' },
              { id: 'se-23', number: 23, text: 'Tells you what he/she wants with one or a few words (e.g., "Juice," "Open," "Kiss").' },
              { id: 'se-24', number: 24, text: 'Shows you he/she understands your simple verbal wish (e.g., "Please show me your toy.").' },
            ],
          },
          {
            label: 'Stage 5b',
            ageRange: '25–30 months',
            items: [
              { id: 'se-25', number: 25, text: 'Plays make-believe (e.g., feeds a doll, plays house, or pretends to be a TV or movie character) with you or others.' },
              { id: 'se-26', number: 26, text: 'Uses words or pictures to tell you what he/she is interested in (e.g., "See truck!").' },
              { id: 'se-27', number: 27, text: 'Uses words with one or more peers.' },
              { id: 'se-28', number: 28, text: 'Uses words or pictures to show what he/she likes or dislikes (e.g., "Want that." "No want.").' },
            ],
          },
          {
            label: 'Stage 6',
            ageRange: '31–42 months',
            items: [
              { id: 'se-29', number: 29, text: 'Plays make-believe with one or more peers.' },
              { id: 'se-30', number: 30, text: 'Plays make-believe with you or others where the story makes sense (e.g., has the bears go visit grandmother and then have a big lunch).' },
              { id: 'se-31', number: 31, text: 'Uses phrases or sentences with you to ask a question about something he/she wants to do (e.g., "Mommy go out?" "What you doing outside?" "Play?").' },
              { id: 'se-32', number: 32, text: 'Can explain why he/she wants something or wants to do something (e.g., "Why do you want the juice?" "Because I\'m thirsty.").' },
              { id: 'se-33', number: 33, text: 'Describes his/her feelings to explain why he/she is doing something or wants something (e.g., "Because I\'m happy/sad/excited.").' },
              { id: 'se-34', number: 34, text: 'Plays make-believe with peers as well as adults where the story makes sense and has many parts to it (e.g., the children go to school, do work, have lunch, and meet an elephant on the way home).' },
              { id: 'se-35', number: 35, text: 'Has conversations with adults and peers that make sense, with four or more back-and-forth exchanges about a variety of topics (e.g., feelings, foods, bedtimes, friends, or school).' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'adaptive-behavior',
    name: 'Adaptive Behavior',
    abbreviation: 'ADBE',
    color: '#5B7B9A',
    colorClass: 'text-[#5B7B9A]',
    bgClass: 'bg-[#5B7B9A]',
    borderClass: 'border-[#5B7B9A]',
    description: 'Assesses daily living skills through caregiver questionnaire, covering receptive and expressive communication, personal care, interpersonal relationships, and play and leisure.',
    administrationType: 'caregiver',
    subdomains: [
      {
        id: 'ab-rec',
        name: 'Receptive',
        abbreviation: 'REC',
        itemCount: 23,
        maxRawScore: 46,
        scoringType: 'adaptive',
        scoringLabels: adaptiveScoring,
        items: [
          { id: 'ab-rec-1', number: 1, text: 'Looks at you when he/she hears your voice.' },
          { id: 'ab-rec-2', number: 2, text: 'Looks at you when you wave to get his/her attention.' },
          { id: 'ab-rec-3', number: 3, text: 'Looks when someone calls his/her name.' },
          { id: 'ab-rec-4', number: 4, text: 'Understands the meaning of at least three basic gestures (e.g., head nod for yes, head shake for no, hand out or give me, reaching, waving, clapping).' },
          { id: 'ab-rec-5', number: 5, text: 'When you look or point at something, looks in that direction.' },
          { id: 'ab-rec-6', number: 6, text: 'Follows directions to do one simple thing (e.g., "Sit down." "Come here.").' },
          { id: 'ab-rec-7', number: 7, text: 'Understands yes.' },
          { id: 'ab-rec-8', number: 8, text: 'Responds to the tone of your words (e.g., he/she responds differently when you say "Come here" with a loving tone than when you say it with an angry tone).' },
          { id: 'ab-rec-9', number: 9, text: 'Understands no.' },
          { id: 'ab-rec-10', number: 10, text: 'Points to at least three real objects when you ask (e.g., a dog).' },
          { id: 'ab-rec-11', number: 11, text: 'Follows directions to do something with one object (e.g., "Bring me the book." "Close the door.").' },
          { id: 'ab-rec-12', number: 12, text: 'Knows at least three of his/her own body parts (e.g., shows you his/her arm when you ask).' },
          { id: 'ab-rec-13', number: 13, text: 'Points to at least three objects shown in pictures when you ask (e.g., a car).' },
          { id: 'ab-rec-14', number: 14, text: 'Points to at least three body parts shown in pictures when you ask (e.g., someone\'s nose).' },
          { id: 'ab-rec-15', number: 15, text: 'Answers questions that use what (e.g., You ask "What is this?" He/she says "A ball.").' },
          { id: 'ab-rec-16', number: 16, text: 'Points to at least three actions shown in pictures when you ask (e.g., someone eating).' },
          { id: 'ab-rec-17', number: 17, text: 'Answers questions that use who (e.g., You ask "Who is that?" He/she says "Auntie Kesha.").' },
          { id: 'ab-rec-18', number: 18, text: 'Pays attention to a story for at least 15 minutes.', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown listening to stories.' },
          { id: 'ab-rec-19', number: 19, text: 'Answers questions that use why (e.g., You ask "Why are you crying?" He/she says "My toy broke.").' },
          { id: 'ab-rec-20', number: 20, text: 'Follows directions to do two things that do not go together (e.g., "Turn off the TV and get my keys.").', scoringCriteria: 'If he/she sometimes does it without reminders but sometimes needs reminders, score 1.' },
          { id: 'ab-rec-21', number: 21, text: 'Answers questions that use when (e.g., You ask "When do you eat breakfast?" He/she says "In the morning.").' },
          { id: 'ab-rec-22', number: 22, text: 'Follows three-step directions (e.g., "Get dressed, eat breakfast, and brush your teeth.").', scoringCriteria: 'If he/she sometimes does it without reminders but sometimes needs reminders, score 1.' },
          { id: 'ab-rec-23', number: 23, text: 'When told to do something a little later, remembers to do it (e.g., "When your show is over, put your dishes in the sink.").', scoringCriteria: 'If he/she sometimes does it without reminders but sometimes needs reminders, score 1.' },
        ],
      },
      {
        id: 'ab-exp',
        name: 'Expressive',
        abbreviation: 'EXP',
        itemCount: 28,
        maxRawScore: 56,
        scoringType: 'adaptive',
        scoringLabels: adaptiveScoring,
        items: [
          { id: 'ab-exp-1', number: 1, text: 'Makes sounds or gestures to get your attention.' },
          { id: 'ab-exp-2', number: 2, text: 'Makes at least three short speech sounds (e.g., mah, bah, ee, oh).', scoringTip: 'Score 2 if he/she did this when younger, but now says words.' },
          { id: 'ab-exp-3', number: 3, text: 'Babbles in strings of sounds (e.g., ba-ba-ba-ba, ma-ma-ma-ma, da-da-da-da).', scoringTip: 'Score 2 if he/she did this when younger, but now says words.' },
          { id: 'ab-exp-4', number: 4, text: 'Makes at least three basic gestures (e.g., nodding head up and down for yes, shaking head for no, reaching for something wanted, waving at people, clapping hands).' },
          { id: 'ab-exp-5', number: 5, text: 'Says "Dada" or "Mama" or another name for parent.' },
          { id: 'ab-exp-6', number: 6, text: 'Says the names of at least three objects (e.g., a ball).', scoringCriteria: 'He/she does not have to say the words perfectly.' },
          { id: 'ab-exp-7', number: 7, text: 'Repeats or tries to repeat words after hearing them (e.g., ball, car, more).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-exp-8', number: 8, text: 'Says the names of at least 10 objects.', scoringTip: 'Score 2 for Yes or 0 for No.' },
          { id: 'ab-exp-9', number: 9, text: 'Says "No." Must actually mean no, not just repeat the word.' },
          { id: 'ab-exp-10', number: 10, text: 'Says one-word requests (e.g., "Want." "More." "Open.").', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-exp-11', number: 11, text: 'Says the names of at least three actions (e.g., eat or eating).', scoringCriteria: 'He/she does not have to say the words perfectly.' },
          { id: 'ab-exp-12', number: 12, text: 'Says at least 50 words.', scoringTip: 'Score 2 for Yes or 0 for No.' },
          { id: 'ab-exp-13', number: 13, text: 'Says his/her own first name or nickname.', scoringCriteria: 'He/she does not have to say the name perfectly.' },
          { id: 'ab-exp-14', number: 14, text: 'Says things using both a noun [a naming word] and a verb [an action word] (e.g., "Mommy stay." "Give ball.").', scoringCriteria: 'He/she does not have to say the words perfectly.' },
          { id: 'ab-exp-15', number: 15, text: 'Knows how to say more than one of something (e.g., "Two cats." "More crackers." "Those flowers.").' },
          { id: 'ab-exp-16', number: 16, text: 'Uses the pronouns I, me, and mine to refer to himself/herself. May make mistakes like "Me want" or "Mine toy."' },
          { id: 'ab-exp-17', number: 17, text: 'Uses words that show who something belongs to (e.g., "This is mine." "Your book." "This is Carol\'s desk.").' },
          { id: 'ab-exp-18', number: 18, text: 'Uses adjectives to describe things (e.g., "Pretty picture." "Big doggie.").', scoringCriteria: 'He/she does not have to say the words perfectly.' },
          { id: 'ab-exp-19', number: 19, text: 'Uses in, on, and under in sentences (e.g., "It\'s in the box." "Ball go under table.").', scoringCriteria: 'His/her sentences do not have to be perfect.' },
          { id: 'ab-exp-20', number: 20, text: 'Asks questions that begin with who (e.g., "Who\'s that?" "Who went to the store?").' },
          { id: 'ab-exp-21', number: 21, text: 'Says how old he/she is when you ask. Holding up fingers counts.' },
          { id: 'ab-exp-22', number: 22, text: 'Says both his/her first name and last name when you ask.', scoringCriteria: 'He/she does not have to say the names perfectly.' },
          { id: 'ab-exp-23', number: 23, text: 'Knows how to say that something happened in the past (e.g., "I walked to the store." "Molly baked a cake.").' },
          { id: 'ab-exp-24', number: 24, text: 'Uses all pronouns (words that refer to himself/herself and others) correctly (e.g., I, she, us, them, your, our, their).' },
          { id: 'ab-exp-25', number: 25, text: 'Tells the basic parts of a well-known story: the characters, what happens, how it ends, etc.', scoringCriteria: 'The story might be from a fairy tale, a book, or a movie.' },
          { id: 'ab-exp-26', number: 26, text: 'Uses behind, in front of, and between in sentences (e.g., "Terrell is behind you." "I walked in front of her." "The ball went between the cars.").' },
          { id: 'ab-exp-27', number: 27, text: 'Tells about one-time events in detail (e.g., when someone asks him/her about a trip).' },
          { id: 'ab-exp-28', number: 28, text: 'Uses two-part sentences joined by and or but (e.g., "She asked me, and I told her no." "Jerome wanted to go, but I didn\'t.").' },
        ],
      },
      {
        id: 'ab-per',
        name: 'Personal (Daily Living Skills)',
        abbreviation: 'PER',
        itemCount: 30,
        maxRawScore: 60,
        scoringType: 'adaptive',
        scoringLabels: adaptiveScoring,
        items: [
          { id: 'ab-per-1', number: 1, text: 'Eats solid foods (e.g., cooked vegetables, chopped meats).' },
          { id: 'ab-per-2', number: 2, text: 'Cooperates when you undress and dress him/her (e.g., raises his/her arms for taking off a top, holds out his/her feet for putting on pants or shoes).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-per-3', number: 3, text: 'Sucks or chews on finger foods (e.g., crackers, cookies, toast).' },
          { id: 'ab-per-4', number: 4, text: 'Cooperates when you wash his/her hands and face (e.g., holds out his/her hands, turns his/her face toward you).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-per-5', number: 5, text: 'Feeds himself/herself with a spoon. May spill.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-6', number: 6, text: 'Takes off his/her shoes and his/her socks.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-7', number: 7, text: 'Drinks from a regular cup or glass. May spill.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-8', number: 8, text: 'Lets someone know when he/she has a wet or dirty diaper or pants.', scoringTip: 'Score 2 if he/she did this when younger, but now uses the toilet.' },
          { id: 'ab-per-9', number: 9, text: 'Feeds himself/herself with a fork. May spill.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-10', number: 10, text: 'Takes off clothing that opens in the front. Does not have to unbutton or unzip it (e.g., a jacket).', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-11', number: 11, text: 'Pulls up clothing that has elastic around the waist (e.g., underwear, sweatpants).', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-12', number: 12, text: 'Drinks from a regular cup or glass without spilling.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-13', number: 13, text: 'Feeds himself/herself with a spoon without spilling.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-14', number: 14, text: 'Washes his/her hands using soap and water and dries them. Does not have to turn the water on and off.', scoringCriteria: 'If he/she sometimes washes and dries without help but sometimes needs help, score 1.' },
          { id: 'ab-per-15', number: 15, text: 'Takes off pullover clothing (e.g., T-shirt, sweatshirt, dress).', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-16', number: 16, text: 'Urinates (goes pee) in a toilet or potty chair.' },
          { id: 'ab-per-17', number: 17, text: 'Puts on his/her shoes. Shoes may be on the wrong feet, and he/she does not have to tie or fasten them.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-18', number: 18, text: 'Wipes or blows his/her nose using tissue, napkin, etc.', scoringCriteria: 'If he/she sometimes does it without help or reminders but sometimes needs help or reminders, score 1.' },
          { id: 'ab-per-19', number: 19, text: 'Puts on clothing that opens in the front. Does not have to zip or button it (e.g., a jacket).', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-20', number: 20, text: 'Defecates (goes poop) in a toilet or potty chair.' },
          { id: 'ab-per-21', number: 21, text: 'Uses the toilet during the day. May need help, but must know when he/she needs to go.', scoringCriteria: 'Score 2 if he/she does not have accidents during the day. Score 1 if he/she has some accidents during the day. Score 0 if he/she has many accidents during the day.' },
          { id: 'ab-per-22', number: 22, text: 'Puts on pullover clothing (e.g., T-shirt, sweatshirt, dress).', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-23', number: 23, text: 'Wipes or cleans his/her face and his/her hands when eating something messy.', scoringCriteria: 'If he/she sometimes does it without help or reminders but sometimes needs help or reminders, score 1.' },
          { id: 'ab-per-24', number: 24, text: 'Puts clothing on with the right side forward and correct side out.', scoringCriteria: 'If he/she sometimes does it without help or reminders but sometimes needs help or reminders, score 1.' },
          { id: 'ab-per-25', number: 25, text: 'Washes and dries his/her face. Does not have to turn the water on and off.', scoringCriteria: 'If he/she sometimes washes and dries without help but sometimes needs help, score 1.' },
          { id: 'ab-per-26', number: 26, text: 'Uses the toilet at night. May need help, but must know when he/she needs to go.', scoringCriteria: 'Score 2 if he/she does not have accidents at night. Score 1 if he/she has some accidents at night. Score 0 if he/she has many accidents at night.' },
          { id: 'ab-per-27', number: 27, text: 'Covers his/her mouth and nose when he/she coughs or sneezes.', scoringCriteria: 'If he/she sometimes does it without reminders but sometimes needs reminders, score 1.' },
          { id: 'ab-per-28', number: 28, text: 'Fastens snaps.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
          { id: 'ab-per-29', number: 29, text: 'Brushes his/her teeth. Must put toothpaste on toothbrush, brush well, and rinse.', scoringCriteria: 'If he/she sometimes does all of the steps without help but sometimes needs help, score 1.' },
          { id: 'ab-per-30', number: 30, text: 'Puts his/her shoes on the correct feet and ties or fastens them.', scoringCriteria: 'If he/she sometimes does it without help but sometimes needs help, score 1.' },
        ],
      },
      {
        id: 'ab-ipr',
        name: 'Interpersonal Relationships',
        abbreviation: 'IPR',
        itemCount: 20,
        maxRawScore: 40,
        scoringType: 'adaptive',
        scoringLabels: adaptiveScoring,
        items: [
          { id: 'ab-ipr-1', number: 1, text: 'Smiles or makes sounds when someone he/she knows comes up to him/her.' },
          { id: 'ab-ipr-2', number: 2, text: 'Looks at your face.' },
          { id: 'ab-ipr-3', number: 3, text: 'Smiles in response to a smile or a friendly voice.' },
          { id: 'ab-ipr-4', number: 4, text: 'Tries to interact with others (e.g., smiles or makes noises at someone, reaches for someone).' },
          { id: 'ab-ipr-5', number: 5, text: 'Reaches for you when you hold out your arms to him/her.', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-ipr-6', number: 6, text: 'Gives affection to people he/she knows (e.g., touches, hugs, kisses, cuddles).' },
          { id: 'ab-ipr-7', number: 7, text: 'Looks around from time to time to be sure that someone who he/she knows is nearby.', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-ipr-8', number: 8, text: 'Acts interested in children his/her age, apart from brothers or sisters (e.g., watches them, smiles at them).' },
          { id: 'ab-ipr-9', number: 9, text: 'Recognizes himself/herself in a mirror or photo.' },
          { id: 'ab-ipr-10', number: 10, text: 'Imitates (copies) you when you make a happy, sad, or surprised face.', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-ipr-11', number: 11, text: 'Realizes when others are happy, sad, surprised, afraid, upset, etc.' },
          { id: 'ab-ipr-12', number: 12, text: 'Imitates (copies) an activity while someone else is doing it (e.g., pretending to shave, put on makeup, vacuum, hammer nails).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-ipr-13', number: 13, text: 'Makes good eye contact when he/she interacts with people.' },
          { id: 'ab-ipr-14', number: 14, text: 'Says how family members are related to him/her (e.g., "That\'s my mom." "He\'s my brother.").' },
          { id: 'ab-ipr-15', number: 15, text: 'Imitates (copies) an activity several hours after watching someone else do it (e.g., pretending to shave, put on makeup, vacuum, hammer nails).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-ipr-16', number: 16, text: 'Has a best friend or a few good friends.', scoringTip: 'Score 2 for Yes or 0 for No.' },
          { id: 'ab-ipr-17', number: 17, text: 'Does things to try to please others (e.g., makes someone a card or gift, helps without being asked).', scoringCriteria: 'If he/she sometimes does it without being told but sometimes has to be told, score 1.' },
          { id: 'ab-ipr-18', number: 18, text: 'Is a good friend: treats his/her friends fairly and with respect, is supportive, etc.', scoringCriteria: 'If he/she has not had any friends for the past year, score 0.' },
          { id: 'ab-ipr-19', number: 19, text: 'Keeps his/her friends over time (e.g., has had the same good friend for over a year).', scoringCriteria: 'If he/she has not had any friends for the past year, score 0.' },
          { id: 'ab-ipr-20', number: 20, text: 'Starts small talk when he/she meets people he/she knows (e.g., "How are you?" "What\'s up?").' },
        ],
      },
      {
        id: 'ab-pla',
        name: 'Play and Leisure',
        abbreviation: 'PLA',
        itemCount: 19,
        maxRawScore: 38,
        scoringType: 'adaptive',
        scoringLabels: adaptiveScoring,
        items: [
          { id: 'ab-pla-1', number: 1, text: 'Shows interest in the things around him/her (e.g., looks or moves around, touches objects or people).' },
          { id: 'ab-pla-2', number: 2, text: 'Responds when you act playful (e.g., smiles, laughs, claps his/her hands).' },
          { id: 'ab-pla-3', number: 3, text: 'Plays baby games like peek-a-boo and patty-cake.', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-pla-4', number: 4, text: 'Plays with one or more children for at least 5 minutes with someone older supervising.', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.', scoringCriteria: 'Playing near other children, but not playing with them, does not count.' },
          { id: 'ab-pla-5', number: 5, text: 'Copies a child playing nearby, even though they are not playing together (e.g., sees another child stacking blocks and then begins to stack blocks).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-pla-6', number: 6, text: 'Would rather play with other children than watch them or play alone.' },
          { id: 'ab-pla-7', number: 7, text: 'Shares his/her toys or other things when he/she is told to.' },
          { id: 'ab-pla-8', number: 8, text: 'Uses things around the house to play make-believe (e.g., pretends a block is a car, a big box is a house).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-pla-9', number: 9, text: 'Moves away from children who try to hurt others or destroy things (e.g., children who are biting, hitting, throwing things, smashing things).', scoringCriteria: 'If he/she sometimes does it without being told but sometimes has to be told, score 1.' },
          { id: 'ab-pla-10', number: 10, text: 'Plays simple make-believe games with other children (e.g., playing "dress-up," pretending to be superheroes).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-pla-11', number: 11, text: 'Plays with others at simple outdoor group games with no score (e.g., tag, jump rope, catch).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-pla-12', number: 12, text: 'Takes turns when asked while playing games or sports.' },
          { id: 'ab-pla-13', number: 13, text: 'Plays make-believe where different children play different roles (e.g., playing "school" or "restaurant," acting out a TV show or movie).', scoringTip: 'Score 2 if he/she did this when younger, but has now outgrown it.' },
          { id: 'ab-pla-14', number: 14, text: 'Asks others to play or spend time together.', scoringCriteria: 'If he/she sometimes does it without being told but sometimes has to be told, score 1.' },
          { id: 'ab-pla-15', number: 15, text: 'Shares his/her toys or other things without having to be told to.' },
          { id: 'ab-pla-16', number: 16, text: 'Takes turns without having to be asked while playing games or sports.' },
          { id: 'ab-pla-17', number: 17, text: 'Asks if it is OK before taking something from someone. Does not just grab it.', scoringCriteria: 'If he/she sometimes does it without being told but sometimes has to be told, score 1.' },
          { id: 'ab-pla-18', number: 18, text: 'Stays out of a group when they let him/her know with words that he/she is not welcome (e.g., "We\'re almost done." "Big kids only.").' },
          { id: 'ab-pla-19', number: 19, text: 'Gets together with two or more others his/her age at someone\'s home.', scoringCriteria: 'Must play with the others to count.' },
        ],
      },
    ],
  },
];

// Generate representative cognitive items
function generateCognitiveItems(): AssessmentItem[] {
  const items: AssessmentItem[] = [
    { id: 'cg-1', number: 1, text: 'Eyes move in the direction of a moving object.' },
    { id: 'cg-2', number: 2, text: 'Habituates to a visual stimulus (looks at a repeated image for shorter periods).' },
    { id: 'cg-3', number: 3, text: 'Shows preference for a novel stimulus over a familiar one.' },
    { id: 'cg-4', number: 4, text: 'Attends to a visual stimulus for at least 3 seconds.' },
    { id: 'cg-5', number: 5, text: 'Visually tracks a slowly moving object from side to side.' },
    { id: 'cg-6', number: 6, text: 'Visually tracks a slowly moving object vertically.' },
    { id: 'cg-7', number: 7, text: 'Visually tracks a slowly moving object in a circular motion.' },
    { id: 'cg-8', number: 8, text: 'Reaches for a visible object.' },
    { id: 'cg-9', number: 9, text: 'Explores objects by mouthing, banging, or shaking.' },
    { id: 'cg-10', number: 10, text: 'Reaches for a second object while holding one.' },
    { id: 'cg-11', number: 11, text: 'Pulls a string to obtain an attached object.' },
    { id: 'cg-12', number: 12, text: 'Looks for a fallen object.' },
    { id: 'cg-13', number: 13, text: 'Uncovers a hidden object (object permanence).' },
    { id: 'cg-14', number: 14, text: 'Plays with a bell purposefully (shakes or rings it).' },
    { id: 'cg-15', number: 15, text: 'Retains two objects (one in each hand).' },
    { id: 'cg-16', number: 16, text: 'Explores cause and effect with toys.' },
    { id: 'cg-17', number: 17, text: 'Finds a hidden object after visible displacement.' },
    { id: 'cg-18', number: 18, text: 'Squeezes or activates a squeaky toy.' },
    { id: 'cg-19', number: 19, text: 'Looks at pictures in a book.' },
    { id: 'cg-20', number: 20, text: 'Pushes a car or rolls a ball.' },
    { id: 'cg-21', number: 21, text: 'Removes a lid from a container.' },
    { id: 'cg-22', number: 22, text: 'Puts objects into a container.' },
    { id: 'cg-23', number: 23, text: 'Dumps objects out of a container.' },
    { id: 'cg-24', number: 24, text: 'Explores objects by turning them over and examining different sides.' },
    { id: 'cg-25', number: 25, text: 'Finds a hidden object after invisible displacement.' },
    { id: 'cg-26', number: 26, text: 'Suspends an object by a string.' },
    { id: 'cg-27', number: 27, text: 'Attends to a story being read.' },
    { id: 'cg-28', number: 28, text: 'Stacks at least 2 blocks.' },
    { id: 'cg-29', number: 29, text: 'Places a round piece in a formboard.' },
    { id: 'cg-30', number: 30, text: 'Uses a stick as a tool to reach an object.' },
    { id: 'cg-31', number: 31, text: 'Stacks at least 4 blocks.' },
    { id: 'cg-32', number: 32, text: 'Places 3 pieces in a formboard.' },
    { id: 'cg-33', number: 33, text: 'Matches objects by color.' },
    { id: 'cg-34', number: 34, text: 'Matches objects by shape.' },
    { id: 'cg-35', number: 35, text: 'Sorts objects into two groups by color.' },
    { id: 'cg-36', number: 36, text: 'Stacks at least 6 blocks.' },
    { id: 'cg-37', number: 37, text: 'Completes a 3-piece puzzle.' },
    { id: 'cg-38', number: 38, text: 'Understands the concept of "one."' },
    { id: 'cg-39', number: 39, text: 'Matches objects by size (big vs. small).' },
    { id: 'cg-40', number: 40, text: 'Sorts objects into two groups by shape.' },
    { id: 'cg-41', number: 41, text: 'Stacks at least 8 blocks.' },
    { id: 'cg-42', number: 42, text: 'Identifies objects by function (e.g., "Which one do we drink from?").' },
    { id: 'cg-43', number: 43, text: 'Matches pictures to objects.' },
    { id: 'cg-44', number: 44, text: 'Understands the concept of "two."' },
    { id: 'cg-45', number: 45, text: 'Compares sizes of objects (bigger/smaller).' },
    { id: 'cg-46', number: 46, text: 'Completes a 4-piece puzzle.' },
    { id: 'cg-47', number: 47, text: 'Sorts objects into three or more groups.' },
    { id: 'cg-48', number: 48, text: 'Counts to 3 with one-to-one correspondence.' },
    { id: 'cg-49', number: 49, text: 'Identifies which group has "more."' },
    { id: 'cg-50', number: 50, text: 'Understands the concept of "three."' },
    { id: 'cg-51', number: 51, text: 'Completes a pattern sequence (AB pattern).' },
    { id: 'cg-52', number: 52, text: 'Counts to 5 with one-to-one correspondence.' },
    { id: 'cg-53', number: 53, text: 'Identifies missing parts of a picture.' },
    { id: 'cg-54', number: 54, text: 'Sorts by two attributes simultaneously.' },
    { id: 'cg-55', number: 55, text: 'Understands "same" and "different."' },
    { id: 'cg-56', number: 56, text: 'Completes a 6-piece puzzle.' },
    { id: 'cg-57', number: 57, text: 'Counts to 10 with one-to-one correspondence.' },
    { id: 'cg-58', number: 58, text: 'Identifies first and last in a sequence.' },
    { id: 'cg-59', number: 59, text: 'Understands the concept of "none" or "zero."' },
    { id: 'cg-60', number: 60, text: 'Compares lengths (longer/shorter).' },
    { id: 'cg-61', number: 61, text: 'Identifies objects that do not belong in a group.' },
    { id: 'cg-62', number: 62, text: 'Arranges objects in order by size (seriation).' },
    { id: 'cg-63', number: 63, text: 'Understands simple time concepts (before/after).' },
    { id: 'cg-64', number: 64, text: 'Counts to 20.' },
    { id: 'cg-65', number: 65, text: 'Recognizes basic shapes (circle, square, triangle).' },
    { id: 'cg-66', number: 66, text: 'Matches quantities to numerals (1-5).' },
    { id: 'cg-67', number: 67, text: 'Understands positional concepts (above, below, beside).' },
    { id: 'cg-68', number: 68, text: 'Completes an 8-piece puzzle.' },
    { id: 'cg-69', number: 69, text: 'Identifies letters of the alphabet.' },
    { id: 'cg-70', number: 70, text: 'Understands ordinal numbers (first, second, third).' },
    { id: 'cg-71', number: 71, text: 'Compares weights (heavier/lighter).' },
    { id: 'cg-72', number: 72, text: 'Identifies rhyming words.' },
    { id: 'cg-73', number: 73, text: 'Counts backward from 5.' },
    { id: 'cg-74', number: 74, text: 'Recognizes written numerals (1-10).' },
    { id: 'cg-75', number: 75, text: 'Understands the concept of addition (1 more).' },
    { id: 'cg-76', number: 76, text: 'Identifies beginning sounds in words.' },
    { id: 'cg-77', number: 77, text: 'Classifies objects by multiple attributes.' },
    { id: 'cg-78', number: 78, text: 'Understands simple subtraction (1 less).' },
    { id: 'cg-79', number: 79, text: 'Creates and extends patterns (ABC pattern).' },
    { id: 'cg-80', number: 80, text: 'Solves simple addition problems using objects.' },
    { id: 'cg-81', number: 81, text: 'Demonstrates understanding of conservation of number.' },
  ];
  return items;
}

function generateReceptiveItems(): AssessmentItem[] {
  const items: AssessmentItem[] = [
    { id: 'rc-1', number: 1, text: 'Responds to a voice by quieting or alerting.' },
    { id: 'rc-2', number: 2, text: 'Turns head toward a sound source.' },
    { id: 'rc-3', number: 3, text: 'Responds to own name by looking or turning.' },
    { id: 'rc-4', number: 4, text: 'Responds to "no" by stopping or pausing activity.' },
    { id: 'rc-5', number: 5, text: 'Responds to familiar words (e.g., "bottle," "mama").' },
    { id: 'rc-6', number: 6, text: 'Follows a simple command with gesture (e.g., "Come here" with arms open).' },
    { id: 'rc-7', number: 7, text: 'Identifies one object when named.' },
    { id: 'rc-8', number: 8, text: 'Identifies three objects when named.' },
    { id: 'rc-9', number: 9, text: 'Follows a simple command without gesture.' },
    { id: 'rc-10', number: 10, text: 'Points to one body part when asked.' },
    { id: 'rc-11', number: 11, text: 'Points to three body parts when asked.' },
    { id: 'rc-12', number: 12, text: 'Identifies one picture when named.' },
    { id: 'rc-13', number: 13, text: 'Identifies three pictures when named.' },
    { id: 'rc-14', number: 14, text: 'Understands action words (e.g., "eating," "sleeping").' },
    { id: 'rc-15', number: 15, text: 'Points to clothing items when named.' },
    { id: 'rc-16', number: 16, text: 'Identifies five pictures when named.' },
    { id: 'rc-17', number: 17, text: 'Follows two-step related commands.' },
    { id: 'rc-18', number: 18, text: 'Understands possessive forms (e.g., "mommy\'s shoe").' },
    { id: 'rc-19', number: 19, text: 'Identifies objects by function (e.g., "Which one do we eat with?").' },
    { id: 'rc-20', number: 20, text: 'Understands size concepts (big/little).' },
    { id: 'rc-21', number: 21, text: 'Identifies actions in pictures.' },
    { id: 'rc-22', number: 22, text: 'Follows two-step unrelated commands.' },
    { id: 'rc-23', number: 23, text: 'Understands pronouns (he, she, they).' },
    { id: 'rc-24', number: 24, text: 'Understands prepositions (in, on, under).' },
    { id: 'rc-25', number: 25, text: 'Identifies colors when named.' },
    { id: 'rc-26', number: 26, text: 'Understands quantity concepts (one, all, more).' },
    { id: 'rc-27', number: 27, text: 'Follows three-step commands.' },
    { id: 'rc-28', number: 28, text: 'Understands comparatives (bigger, smaller, longer).' },
    { id: 'rc-29', number: 29, text: 'Identifies objects by two attributes (e.g., "big red ball").' },
    { id: 'rc-30', number: 30, text: 'Understands negation (e.g., "not the big one").' },
    { id: 'rc-31', number: 31, text: 'Understands past tense verbs.' },
    { id: 'rc-32', number: 32, text: 'Understands "if-then" statements.' },
    { id: 'rc-33', number: 33, text: 'Identifies objects described by category (e.g., "Find the animal").' },
    { id: 'rc-34', number: 34, text: 'Understands superlatives (biggest, smallest).' },
    { id: 'rc-35', number: 35, text: 'Follows complex directions with embedded clauses.' },
    { id: 'rc-36', number: 36, text: 'Understands temporal concepts (before, after, first, last).' },
    { id: 'rc-37', number: 37, text: 'Identifies objects by exclusion (e.g., "Find the one that is NOT a fruit").' },
    { id: 'rc-38', number: 38, text: 'Understands passive voice sentences.' },
    { id: 'rc-39', number: 39, text: 'Follows directions with multiple modifiers.' },
    { id: 'rc-40', number: 40, text: 'Understands complex question forms (why, how, when).' },
    { id: 'rc-41', number: 41, text: 'Identifies absurdities in sentences or pictures.' },
    { id: 'rc-42', number: 42, text: 'Understands figurative language (simple idioms).' },
  ];
  return items;
}

function generateExpressiveItems(): AssessmentItem[] {
  const items: AssessmentItem[] = [
    { id: 'ec-1', number: 1, text: 'Produces vowel-like sounds (cooing).' },
    { id: 'ec-2', number: 2, text: 'Laughs or chuckles.' },
    { id: 'ec-3', number: 3, text: 'Produces consonant-vowel combinations (babbling).' },
    { id: 'ec-4', number: 4, text: 'Uses gestures to communicate (reaching, pointing).' },
    { id: 'ec-5', number: 5, text: 'Produces varied babbling with different consonants.' },
    { id: 'ec-6', number: 6, text: 'Uses jargon (babbling with sentence-like intonation).' },
    { id: 'ec-7', number: 7, text: 'Says first true word (other than "mama" or "dada").' },
    { id: 'ec-8', number: 8, text: 'Uses 3 or more words consistently.' },
    { id: 'ec-9', number: 9, text: 'Names one object.' },
    { id: 'ec-10', number: 10, text: 'Uses 8 or more words.' },
    { id: 'ec-11', number: 11, text: 'Names one picture.' },
    { id: 'ec-12', number: 12, text: 'Combines two words (e.g., "more milk," "daddy go").' },
    { id: 'ec-13', number: 13, text: 'Uses 20 or more words.' },
    { id: 'ec-14', number: 14, text: 'Names three pictures.' },
    { id: 'ec-15', number: 15, text: 'Uses three-word phrases.' },
    { id: 'ec-16', number: 16, text: 'Uses pronouns (I, me, you).' },
    { id: 'ec-17', number: 17, text: 'Uses plural forms (e.g., "dogs," "cats").' },
    { id: 'ec-18', number: 18, text: 'Uses possessive forms (e.g., "my," "mine").' },
    { id: 'ec-19', number: 19, text: 'Names five pictures.' },
    { id: 'ec-20', number: 20, text: 'Uses past tense (e.g., "walked," "ate").' },
    { id: 'ec-21', number: 21, text: 'Uses four-word sentences.' },
    { id: 'ec-22', number: 22, text: 'Asks "what" and "where" questions.' },
    { id: 'ec-23', number: 23, text: 'Uses prepositions in speech (in, on, under).' },
    { id: 'ec-24', number: 24, text: 'Names actions in pictures.' },
    { id: 'ec-25', number: 25, text: 'Uses articles (a, the) in speech.' },
    { id: 'ec-26', number: 26, text: 'Asks "why" questions.' },
    { id: 'ec-27', number: 27, text: 'Uses five or more word sentences.' },
    { id: 'ec-28', number: 28, text: 'Describes function of objects.' },
    { id: 'ec-29', number: 29, text: 'Uses conjunctions (and, but, because).' },
    { id: 'ec-30', number: 30, text: 'Tells a simple story with a beginning, middle, and end.' },
    { id: 'ec-31', number: 31, text: 'Uses irregular past tense verbs correctly.' },
    { id: 'ec-32', number: 32, text: 'Defines simple words.' },
    { id: 'ec-33', number: 33, text: 'Uses complex sentences with embedded clauses.' },
    { id: 'ec-34', number: 34, text: 'Describes similarities and differences between objects.' },
    { id: 'ec-35', number: 35, text: 'Uses future tense (e.g., "I will go," "I\'m going to").' },
    { id: 'ec-36', number: 36, text: 'Retells a story with details in correct sequence.' },
    { id: 'ec-37', number: 37, text: 'Uses comparative and superlative forms in speech.' },
  ];
  return items;
}

function generateFineMotorItems(): AssessmentItem[] {
  const items: AssessmentItem[] = [
    { id: 'fm-1', number: 1, text: 'Hands are predominantly fisted (reflex grasp).' },
    { id: 'fm-2', number: 2, text: 'Hands are open at rest at least half the time.' },
    { id: 'fm-3', number: 3, text: 'Reaches toward an object with both hands.' },
    { id: 'fm-4', number: 4, text: 'Grasps a rattle placed in hand.' },
    { id: 'fm-5', number: 5, text: 'Reaches for and contacts an object.' },
    { id: 'fm-6', number: 6, text: 'Uses whole hand (palmar) grasp on a cube.' },
    { id: 'fm-7', number: 7, text: 'Transfers an object from one hand to the other.' },
    { id: 'fm-8', number: 8, text: 'Uses radial-palmar grasp (thumb side of hand).' },
    { id: 'fm-9', number: 9, text: 'Uses raking grasp to pick up a small object.' },
    { id: 'fm-10', number: 10, text: 'Uses inferior pincer grasp (thumb and side of index finger).' },
    { id: 'fm-11', number: 11, text: 'Pokes with index finger.' },
    { id: 'fm-12', number: 12, text: 'Uses neat pincer grasp (thumb and fingertip).' },
    { id: 'fm-13', number: 13, text: 'Places small objects into a container.' },
    { id: 'fm-14', number: 14, text: 'Turns pages of a board book (may turn multiple pages).' },
    { id: 'fm-15', number: 15, text: 'Scribbles spontaneously with a crayon.' },
    { id: 'fm-16', number: 16, text: 'Places pegs in a pegboard.' },
    { id: 'fm-17', number: 17, text: 'Stacks 2 blocks.' },
    { id: 'fm-18', number: 18, text: 'Turns pages one at a time.' },
    { id: 'fm-19', number: 19, text: 'Stacks 4 blocks.' },
    { id: 'fm-20', number: 20, text: 'Imitates a vertical line with a crayon.' },
    { id: 'fm-21', number: 21, text: 'Imitates a horizontal line.' },
    { id: 'fm-22', number: 22, text: 'Stacks 6 blocks.' },
    { id: 'fm-23', number: 23, text: 'Snips with scissors.' },
    { id: 'fm-24', number: 24, text: 'Imitates a circle.' },
    { id: 'fm-25', number: 25, text: 'Strings beads.' },
    { id: 'fm-26', number: 26, text: 'Stacks 8 blocks.' },
    { id: 'fm-27', number: 27, text: 'Copies a circle.' },
    { id: 'fm-28', number: 28, text: 'Cuts across a piece of paper with scissors.' },
    { id: 'fm-29', number: 29, text: 'Copies a cross (+).' },
    { id: 'fm-30', number: 30, text: 'Traces a line with a crayon.' },
    { id: 'fm-31', number: 31, text: 'Cuts along a straight line.' },
    { id: 'fm-32', number: 32, text: 'Copies a square.' },
    { id: 'fm-33', number: 33, text: 'Draws a person with at least 3 body parts.' },
    { id: 'fm-34', number: 34, text: 'Cuts along a curved line.' },
    { id: 'fm-35', number: 35, text: 'Copies a triangle.' },
    { id: 'fm-36', number: 36, text: 'Draws a person with at least 6 body parts.' },
    { id: 'fm-37', number: 37, text: 'Colors within lines.' },
    { id: 'fm-38', number: 38, text: 'Copies a diamond.' },
    { id: 'fm-39', number: 39, text: 'Prints own first name.' },
    { id: 'fm-40', number: 40, text: 'Copies simple letters.' },
    { id: 'fm-41', number: 41, text: 'Draws recognizable pictures.' },
    { id: 'fm-42', number: 42, text: 'Cuts out a circle.' },
    { id: 'fm-43', number: 43, text: 'Copies numbers 1-5.' },
    { id: 'fm-44', number: 44, text: 'Draws a person with at least 8 body parts.' },
    { id: 'fm-45', number: 45, text: 'Prints simple words.' },
    { id: 'fm-46', number: 46, text: 'Uses a mature tripod grasp on writing tools.' },
  ];
  return items;
}

function generateGrossMotorItems(): AssessmentItem[] {
  const items: AssessmentItem[] = [
    { id: 'gm-1', number: 1, text: 'Lifts head briefly when held at shoulder.' },
    { id: 'gm-2', number: 2, text: 'Holds head steady when held upright.' },
    { id: 'gm-3', number: 3, text: 'Lifts head 45 degrees in prone position.' },
    { id: 'gm-4', number: 4, text: 'Lifts head 90 degrees in prone position.' },
    { id: 'gm-5', number: 5, text: 'Bears weight on forearms in prone.' },
    { id: 'gm-6', number: 6, text: 'Rolls from back to side.' },
    { id: 'gm-7', number: 7, text: 'Rolls from stomach to back.' },
    { id: 'gm-8', number: 8, text: 'Rolls from back to stomach.' },
    { id: 'gm-9', number: 9, text: 'Sits with support.' },
    { id: 'gm-10', number: 10, text: 'Sits momentarily without support.' },
    { id: 'gm-11', number: 11, text: 'Sits independently for 30 seconds.' },
    { id: 'gm-12', number: 12, text: 'Sits independently and reaches for toys.' },
    { id: 'gm-13', number: 13, text: 'Gets to sitting position independently.' },
    { id: 'gm-14', number: 14, text: 'Pivots in sitting.' },
    { id: 'gm-15', number: 15, text: 'Crawls on stomach (commando crawl).' },
    { id: 'gm-16', number: 16, text: 'Crawls on hands and knees.' },
    { id: 'gm-17', number: 17, text: 'Pulls to standing at furniture.' },
    { id: 'gm-18', number: 18, text: 'Stands holding onto furniture.' },
    { id: 'gm-19', number: 19, text: 'Cruises along furniture (sideways stepping).' },
    { id: 'gm-20', number: 20, text: 'Stands alone momentarily.' },
    { id: 'gm-21', number: 21, text: 'Stands alone for 10 seconds.' },
    { id: 'gm-22', number: 22, text: 'Takes 2-3 independent steps.' },
    { id: 'gm-23', number: 23, text: 'Walks independently.' },
    { id: 'gm-24', number: 24, text: 'Walks carrying a toy.' },
    { id: 'gm-25', number: 25, text: 'Stoops and recovers.' },
    { id: 'gm-26', number: 26, text: 'Walks backward.' },
    { id: 'gm-27', number: 27, text: 'Walks up stairs with hand held.' },
    { id: 'gm-28', number: 28, text: 'Walks down stairs with hand held.' },
    { id: 'gm-29', number: 29, text: 'Runs stiffly.' },
    { id: 'gm-30', number: 30, text: 'Kicks a ball forward.' },
    { id: 'gm-31', number: 31, text: 'Throws a ball overhand.' },
    { id: 'gm-32', number: 32, text: 'Jumps in place with both feet.' },
    { id: 'gm-33', number: 33, text: 'Walks up stairs alternating feet with rail.' },
    { id: 'gm-34', number: 34, text: 'Walks on tiptoes.' },
    { id: 'gm-35', number: 35, text: 'Stands on one foot momentarily.' },
    { id: 'gm-36', number: 36, text: 'Jumps forward.' },
    { id: 'gm-37', number: 37, text: 'Walks down stairs alternating feet with rail.' },
    { id: 'gm-38', number: 38, text: 'Catches a large ball with both arms.' },
    { id: 'gm-39', number: 39, text: 'Pedals a tricycle.' },
    { id: 'gm-40', number: 40, text: 'Runs smoothly.' },
    { id: 'gm-41', number: 41, text: 'Stands on one foot for 3 seconds.' },
    { id: 'gm-42', number: 42, text: 'Hops on one foot.' },
    { id: 'gm-43', number: 43, text: 'Walks up stairs alternating feet without rail.' },
    { id: 'gm-44', number: 44, text: 'Walks along a line.' },
    { id: 'gm-45', number: 45, text: 'Catches a bounced ball.' },
    { id: 'gm-46', number: 46, text: 'Walks down stairs alternating feet without rail.' },
    { id: 'gm-47', number: 47, text: 'Stands on one foot for 5 seconds.' },
    { id: 'gm-48', number: 48, text: 'Hops on one foot 3 or more times.' },
    { id: 'gm-49', number: 49, text: 'Gallops.' },
    { id: 'gm-50', number: 50, text: 'Skips.' },
    { id: 'gm-51', number: 51, text: 'Stands on one foot for 10 seconds.' },
    { id: 'gm-52', number: 52, text: 'Walks on a balance beam.' },
    { id: 'gm-53', number: 53, text: 'Catches a small ball with hands only.' },
    { id: 'gm-54', number: 54, text: 'Jumps over an obstacle.' },
    { id: 'gm-55', number: 55, text: 'Bounces and catches a ball.' },
    { id: 'gm-56', number: 56, text: 'Hops on alternating feet.' },
    { id: 'gm-57', number: 57, text: 'Performs a broad jump.' },
    { id: 'gm-58', number: 58, text: 'Walks backward on a line.' },
  ];
  return items;
}

export const ageRanges = [
  { value: '0-1', label: '16 days – 1 month' },
  { value: '1-2', label: '1 – 2 months' },
  { value: '2-3', label: '2 – 3 months' },
  { value: '3-4', label: '3 – 4 months' },
  { value: '4-5', label: '4 – 5 months' },
  { value: '5-6', label: '5 – 6 months' },
  { value: '6-7', label: '6 – 7 months' },
  { value: '7-8', label: '7 – 8 months' },
  { value: '8-9', label: '8 – 9 months' },
  { value: '9-10', label: '9 – 10 months' },
  { value: '10-11', label: '10 – 11 months' },
  { value: '11-12', label: '11 – 12 months' },
  { value: '12-14', label: '12 – 14 months' },
  { value: '14-16', label: '14 – 16 months' },
  { value: '16-18', label: '16 – 18 months' },
  { value: '18-20', label: '18 – 20 months' },
  { value: '20-22', label: '20 – 22 months' },
  { value: '22-24', label: '22 – 24 months' },
  { value: '24-27', label: '24 – 27 months' },
  { value: '27-30', label: '27 – 30 months' },
  { value: '30-33', label: '30 – 33 months' },
  { value: '33-36', label: '33 – 36 months' },
  { value: '36-39', label: '36 – 39 months' },
  { value: '39-42', label: '39 – 42 months' },
];

export function getDescriptiveClassification(standardScore: number): { label: string; color: string } {
  if (standardScore >= 130) return { label: 'Extremely High', color: '#059669' };
  if (standardScore >= 120) return { label: 'Very High', color: '#10B981' };
  if (standardScore >= 110) return { label: 'High Average', color: '#34D399' };
  if (standardScore >= 90) return { label: 'Average', color: '#6B7280' };
  if (standardScore >= 80) return { label: 'Low Average', color: '#F59E0B' };
  if (standardScore >= 70) return { label: 'Borderline', color: '#EF4444' };
  return { label: 'Extremely Low', color: '#DC2626' };
}
