// DAYC-2 Spanish Assessment Data
// Auto-generated from Excel template

export interface DAYC2Item {
  number: number;
  description: string;
}

export interface DAYC2Domain {
  id: string;
  name: string;
  items: DAYC2Item[];
  entryPoints: { label: string; startItem: number }[];
}

export const SOCIALEMOTIONAL_ITEMS: DAYC2Item[] = [
  { number: 1, description: 'Relaja el cuerpo cuando lo sostiene' },
  { number: 2, description: 'Deja de llorar cuando se le habla, se levanta o se consuela' },
  { number: 3, description: 'Establece contacto visual durante unos segundos' },
  { number: 4, description: 'Mira la cara de un adulto durante varios segundos' },
  { number: 5, description: 'Sonríe reflexivamente' },
  { number: 6, description: 'Interactúa sonriendo y arrullando' },
  { number: 7, description: 'Reconoce caras y objetos familiares (padre, biberón). Reacciona agitando los brazos y las piernas o chillando de emoción' },
  { number: 8, description: 'Expresa sentimientos como ira, cansancio, emoción, hambre.' },
  { number: 9, description: 'Se ríe, chilla o muestra placer cuando el cuidador involucra al niño en el juego' },
  { number: 10, description: 'Se consuela a sí mismo' },
  { number: 11, description: 'Se ríe cuando la cabeza está cubierta con un paño' },
  { number: 12, description: 'Conoce la diferencia entre el cuidador y un extraño' },
  { number: 13, description: 'Sonríe o da palmaditas a su propia imagen en el espejo' },
  { number: 14, description: 'Vocaliza cuando se llama su nombre' },
  { number: 15, description: 'Extiende los brazos a las personas conocidas' },
  { number: 16, description: 'Muestra preferencia por ciertos juguetes, actividades o lugares' },
  { number: 17, description: 'Expresa cariño (beso, abrazo)' },
  { number: 18, description: 'Juega juegos simples (peek a boo)' },
  { number: 19, description: 'Imita expresiones faciales, acciones y sonidos' },
  { number: 20, description: 'Repite la actividad que provoca la risa o una respuesta positiva de los demás' },
  { number: 21, description: 'Trae juguetes para compartir con la cuidadora' },
  { number: 22, description: 'Juega bien por un breve período de tiempo con otros 2-3 niños, alguna interacción con los niños' },
  { number: 23, description: 'Saluda a personas conocidas con abrazos o otro gesto apropiado' },
  { number: 24, description: 'Se separa de los padres en un lugar conocido sin llorar' },
  { number: 25, description: 'Intentos de consolar a otros en apuros' },
  { number: 26, description: 'Insiste en tratar de hacer las cosas sin ayuda' },
  { number: 27, description: 'Disfruta del juego simple de fantasía' },
  { number: 28, description: 'Muestra orgullo por los logros' },
  { number: 29, description: 'Escucha tranquilamente una historia, música, película o televisión' },
  { number: 30, description: 'Canta canción familiar con un adulto' },
  { number: 31, description: 'Usa "por favor" y "gracias" apropiadamente, es posible que deba recordárse' },
  { number: 32, description: 'Pide ayuda' },
  { number: 33, description: 'Mira a la persona cuando habla con ellas' },
  { number: 34, description: 'Generalmente toma turnos' },
  { number: 35, description: 'Sabe cuando alguien está feliz o triste' },
  { number: 36, description: 'Evita los peligros comunes (estufa, cuchillos, fuego)' },
  { number: 37, description: 'Juega a vestirse' },
  { number: 38, description: 'De exhibe repitiendo rimas, canciones o bailes para otros' },
  { number: 39, description: 'Cambia de una actividad a otra cuando lo requiere un adulto' },
  { number: 40, description: 'Interactúa apropiadamente con otros durante juegos o actividades grupales' },
  { number: 41, description: 'Conoce y sigue las reglas del salón de clases' },
  { number: 42, description: 'Gana la atención de sus compañeros de manera apropiada' },
  { number: 43, description: 'Juega juegos de mesa o cartas en grupo' },
  { number: 44, description: 'Se ofrece para hacer actividades' },
  { number: 45, description: 'Se calma después del juego activo' },
  { number: 46, description: 'Le gustan los juegos competitivos' },
  { number: 47, description: 'Devuelve los objetos a sus lugares apropiados' },
  { number: 48, description: 'Acepta burlas suaves y amistosas' },
  { number: 49, description: 'Explica las reglas de un juego a otros' },
  { number: 50, description: 'Expresa enojo con palabras no agresivas en lugar de acciones físicas.' },
  { number: 51, description: 'Ofrece un artículo o actividad a otro a cambio de un artículo o actividad' },
  { number: 52, description: 'Acepta críticas válidas sin llorar, hacer pucheros o negarse a continuar.' },
  { number: 53, description: 'Pregunta antes de usar las pertenencias de otra persona' },
  { number: 54, description: 'Proporciona u ofrece asistencia a otros cuando sea apropiado.' },
  { number: 55, description: 'Ayuda con proyectos grupales' },
  { number: 56, description: 'Finaliza las conversaciones con un "adiós" u otra frase apropiada' },
  { number: 57, description: 'Se disculpa si hiere los sentimientos de alguien' },
  { number: 58, description: 'Mantiene la calma cuando se le niegan pequeñas solicitudes (por ejemplo, no puede comer un refrigerio).' },
  { number: 59, description: 'Trabaja solo en la tarea durante 20 a 30 minutos' },
  { number: 60, description: 'Completa juegos de lápiz y papel (por ejemplo, unir puntos, imágenes ocultas, laberintos)' },
  { number: 61, description: 'Inicia actividades grupales' },
  { number: 62, description: 'Felicita a las demás cuando sea apropiado' },
  { number: 63, description: 'Contesta el teléfono, recuerda un mensaje sencillo y se lo entrega a la persona correcta.' },
];

export const ADAPTIVEBAHAVIOR_ITEMS: DAYC2Item[] = [
  { number: 1, description: 'Mantiene la temperatura corporal sin ayuda externa' },
  { number: 2, description: 'Forma un sello ajustado alrededor del pezón al succionar' },
  { number: 3, description: 'Traga liquido sin dificultad' },
  { number: 4, description: 'Coordina chupar, tragar y respirar' },
  { number: 5, description: 'Abre la boca en previsión de la alimentación' },
  { number: 6, description: 'Disfruta el baño' },
  { number: 7, description: 'Duerme por intervalos de 4-10 horas' },
  { number: 8, description: 'Cierra los labios al tragar' },
  { number: 9, description: 'Come alimentos hechos puré' },
  { number: 10, description: 'Usa la lengua para mover la comida en la boca' },
  { number: 11, description: 'Muestra gustos y disgustos definidos por varios alimentos' },
  { number: 12, description: 'Duerme toda la noche, toma 2-3 siestas por día' },
  { number: 13, description: 'Sostiene o sostiene un biberón para alimentarse a sí mismo' },
  { number: 14, description: 'Se quita los calcetines' },
  { number: 15, description: 'Se alimenta con alimentos para comer con los dedos' },
  { number: 16, description: 'Mastica alimentos con textura' },
  { number: 17, description: 'Ayuda a vestirse y desvestirse' },
  { number: 18, description: 'Duerme toda la noche, toma 1-2 siestas durante el día' },
  { number: 19, description: 'Bebe de una taza abierta sostenida por un adulto' },
  { number: 20, description: 'Bebe de una taza con una popote' },
  { number: 21, description: 'Ayuda con las tareas domésticas sencillas, ayuda a limpiar' },
  { number: 22, description: 'Se queja cuando hay que cambiarle el pañal' },
  { number: 23, description: 'Trata de lavarse las manos y la cara' },
  { number: 24, description: 'Se quita la ropa suelta como chaqueta, pantalones cortos o camisa sin ayuda' },
  { number: 25, description: 'Abre la puerta usando la manija o la perilla' },
  { number: 26, description: 'Se pone ropa sencilla (gorra o pantalones)de forma independiente' },
  { number: 27, description: 'Come independientemente una comida completa con una cuchara' },
  { number: 28, description: 'Se limpia la nariz, puede ser necesario que se le recuerden' },
  { number: 29, description: 'Se sienta en la taza del bano durante al menos un minuto supervisado' },
  { number: 30, description: 'Verbaliza las necesidades de la vejiga o cuando necesita usar el bano la mayor parte del tiempo' },
  { number: 31, description: 'Se lava las manos y la cara de forma independiente' },
  { number: 32, description: 'Limpia los derrames, consiguiendo su propio paño' },
  { number: 33, description: 'Muestra cuidado al manipular a un bebé o un animal pequeña' },
  { number: 34, description: 'Sirve leche o jugo con algo de ayuda' },
  { number: 35, description: 'Le dice al adulto que necesita ir al baño a tiempo para ir al baño' },
  { number: 36, description: 'Asume la responsabilidad de ir al baño, puede necesitar ayuda para limpiarse' },
  { number: 37, description: 'Bebe agua del fregadero sin ayuda' },
  { number: 38, description: 'Se cepilla los dientes de forma independiente' },
  { number: 39, description: 'Reconoce su propia casa' },
  { number: 40, description: 'Manipula botones grandes o broches' },
  { number: 41, description: 'Cubre la boca o la nariz al toser o estornudar' },
  { number: 42, description: 'Duerme toda la noche sin mojarse' },
  { number: 43, description: 'Cuelga la ropa' },
  { number: 44, description: 'Se viste solo excepto por los cordones de los zapatos' },
  { number: 45, description: 'Se sirve solo en la mesa' },
  { number: 46, description: 'Segido quiere privacidad en el baño' },
  { number: 47, description: 'Responde preguntas de qué hacer si (por ejemplo, "¿Qué harías si te cortas el dedo?")' },
  { number: 48, description: 'Se abrocha el cinturón de seguridad en el automóvil de forma independiente.' },
  { number: 49, description: 'Cruza la calle de manera segura (por ejemplo, mira a ambos lados, usa cruces peatonales)' },
  { number: 50, description: 'Pone los platos sucios en el fregadero o en el lavavajillas' },
  { number: 51, description: 'Pide que le pasen comida en la mesa' },
  { number: 52, description: 'Selecciona ropa apropiada para la temperatura y la ocasión.' },
  { number: 53, description: 'Hace su propia cama; tal vez sea necesario recordarlo' },
  { number: 54, description: 'Establece y recoge la mesa sin ayuda.' },
  { number: 55, description: 'Usa un cuchillo de mesa para untar mantequilla blanda, gelatina o mantequilla de maní' },
  { number: 56, description: 'Planea con anticipación para satisfacer las necesidades de ir al baño antes de comenzar una actividad.' },
  { number: 57, description: 'Se ducha o baña de forma independiente' },
  { number: 58, description: 'Limpia la encimera o la superficie de trabajo con una esponja o toallas de papel' },
  { number: 59, description: 'Quita el polvo de los muebles' },
  { number: 60, description: 'Hace desayuno y almuerzo sencillos' },
  { number: 61, description: 'Se lava el propio cabello' },
  { number: 62, description: 'Se ocupa de cortes menores (limpia y aplica vendajes)' },
  { number: 63, description: 'Anda en bicicleta de forma segura sin ruedas auxiliares' },
  { number: 64, description: 'Corta los alimentos (incluida la carne) en trozos pequeños' },
];

export const RECEPTIVECOMM_ITEMS: DAYC2Item[] = [
  { number: 1, description: 'Frecuencia respiratoria normal' },
  { number: 2, description: 'reacciona a ruidos fuertes parpadeando, moviendo brazos o piernas, o deteniéndose' },
  { number: 3, description: 'silenciado por la música' },
  { number: 4, description: 'Gira la cabeza hacia la voz cuando alguien le habla' },
  { number: 5, description: 'sonríe a la persona que está hablando o gesticulando' },
  { number: 6, description: 'Se gira y mira hacia el ruido' },
  { number: 7, description: 'Detiene brevemente la actividad cuando se llama el nombre' },
  { number: 8, description: 'responde con gestos apropiados a "arriba"; "adiós;" u otras rutinas' },
  { number: 9, description: 'Mueve el cuerpo a la música' },
  { number: 10, description: 'Detiene la actividad brevemente cuando le dicen "no"' },
  { number: 11, description: 'sigue órdenes simples (por ejemplo, "Dale la taza a mamá:")' },
  { number: 12, description: 'responde a preguntas de "dónde" (por ejemplo, "¿Dónde está la bola?" Puede señalar, indicar la ubicación o ir a por la pelota.)' },
  { number: 13, description: 'Cuando se le pregunte, señalará cinco o más personas, animales o juguetes familiares' },
  { number: 14, description: 'Sigue las instrucciones para colocar un objeto "en" y "en" otro' },
  { number: 15, description: 'indica "sí" o "no" (o movimiento adecuado de la cabeza) en respuesta a las preguntas' },
  { number: 16, description: 'Señala tres partes del cuerpo cuando se le pregunta' },
  { number: 17, description: 'lleva a cabo instrucciones de dos pasos relacionadas (por ejemplo, "Ve a la mesa y tráeme el juguete:")' },
  { number: 18, description: 'Punta a seis partes del cuerpo cuando se le pregunta' },
  { number: 19, description: 'señala 15 o más imágenes de objetos comunes cuando se les nombra' },
  { number: 20, description: 'entiende al menos tres posesivos (por ejemplo, el mío, el tuyo y el de niño; "¿Esta es tu pelota?" "Enséñame la comida del perro :\')' },
  { number: 21, description: 'señala cinco o más objetos comunes descritos por su uso (por ejemplo, "Muéstrame con qué comes:\')' },
  { number: 22, description: 'ejecuta comandos de dos pasos no relacionados (por ejemplo, "Pon la bola en la estantería y luego aplaude:\')' },
  { number: 23, description: 'entiende negativo (por ejemplo, "Que no es ... ¿Rojo, el perro?")' },
  { number: 24, description: 'sabe "grande" y "pequeño" (por ejemplo, "Lánzame la pelota grande:\')' },
  { number: 25, description: 'responde a preguntas de "quién" y "de quién" (por ejemplo, "¿Quién lleva una camiseta roja hoy?")' },
  { number: 26, description: 'sigue las instrucciones de colocar un objeto "al lado" y "debajo" de otro' },
  { number: 27, description: 'entiende "delante de" y "detrás" (por ejemplo, "¿Qué hay detrás de la pantalla?")' },
  { number: 28, description: 'responde a preguntas de comprensión cuando se le cuenta un cuento corto' },
  { number: 29, description: 'demuestra comprensión de las oraciones pasivas (por ejemplo, "Muéstrame que el tren fue empujado por el vagón:")' },
  { number: 30, description: 'ejecuta comandos de tres pasos que no están relacionados (por ejemplo, "Pon la pelota sobre la mesa, cierra la puerta y date la vuelta:\')' },
  { number: 31, description: 'indica si dos palabras riman o tienen el mismo sonido final para al menos tres pares de palabras (por ejemplo, "¿El gato y el pato tienen el mismo sonido final?")' },
  { number: 32, description: 'responde a preguntas que involucran conceptos de tiempo (por ejemplo, "¿Cuándo comemos?")' },
  { number: 33, description: 'entiende las cuatro estaciones del año y lo que haces en cada una (por ejemplo, "¿Qué hacemos en verano?")' },
  { number: 34, description: 'puede identificar al menos tres opuestos usando imágenes u objetos ("Muéstrame lo opuesto de ... grande/pequeño, caliente/frío, alto/bajo:\')' },
  { number: 35, description: 'identifica "izquierda" y "derecha" en su propio cuerpo (por ejemplo, "Levanta la mano derecha").' },
  { number: 36, description: 'puede identificar al menos tres unidades de moneda (por ejemplo, "Apunta al ... penny, dólar, cora")' },
  { number: 37, description: 'puede identificar al menos tres oraciones completas ("Dime si esto es una oración completa:\' por ejemplo, pero cafe; El chico salió corriendo.)' },
];

export const EXPRESSIVECOMM_ITEMS: DAYC2Item[] = [
  { number: 1, description: 'tiene un llanto fuerte' },
  { number: 2, description: 'hace ruidos de succión' },
  { number: 3, description: 'Llora cuando tiene hambre o se siente incómodo' },
  { number: 4, description: 'hace ruidos distintos a llanto (por ejemplo, arrullos, gorgoteos)' },
  { number: 5, description: 'tiene diferentes gritos de dolor, hambre o incomodidad' },
  { number: 6, description: 'produce tres o más sonidos vocálicos simples (por ejemplo, ah, eh, uh)' },
  { number: 7, description: 'se ríe a carcajadas' },
  { number: 8, description: 'produce tres o más consonantes, como /b/, /m/ o /d/' },
  { number: 9, description: 'produce una cadena de sonidos consonántico-vocal (por ejemplo, ba-ba, da-da)' },
  { number: 10, description: 'Usa la palabra para progenitor o cuidador de forma discriminada (por ejemplo, mamá, papá, abuela)' },
  { number: 11, description: 'Utiliza patrones de inflexión al vocalizar (por ejemplo, eleva el tono como si hiciera una pregunta)' },
  { number: 12, description: 'De forma espontánea saluda y despide familiares' },
  { number: 13, description: 'tiene una palabra, sonido o señal para "beber"' },
  { number: 14, description: 'Usa al menos cinco palabras' },
  { number: 15, description: 'dice una palabra que transmite todo el pensamiento; El significado depende del contexto (por ejemplo, "galleta" puede significar "quiere más" o "la galleta se cayó")' },
  { number: 16, description: 'puede nombrar personajes o objetos conocidos vistos en la televisión o en películas (por ejemplo, Big Bird/Abelardo)' },
  { number: 17, description: 'conoce los nombres de dos o más compañeros de juego' },
  { number: 18, description: 'usa entre 10 y 15 palabras espontáneamente' },
  { number: 19, description: 'produce tres o más frases de dos palabras (por ejemplo, más jugo)' },
  { number: 20, description: 'nombra ocho o más imágenes de objetos familiare' },
  { number: 21, description: 'susurros' },
  { number: 22, description: 'Utiliza oraciones de tres o más palabras' },
  { number: 23, description: 'Utiliza al menos 50 palabras diferentes en el habla espontánea' },
  { number: 24, description: 'describe lo que está haciendo (por ejemplo, responde a "¿Qué estás haciendo?")' },
  { number: 25, description: 'hace preguntas de "qué" o "dónde" (por ejemplo, "¿Dónde está mi pelota?")' },
  { number: 26, description: 'Utiliza cinco o más plurales regulares (por ejemplo, niños, juguetes)' },
  { number: 27, description: 'cambia el habla según el oyente (por ejemplo, habla de forma diferente a los bebés que a los adultos)' },
  { number: 28, description: 'da nombre completo cuando se solicita (por ejemplo, "¿Cómo te llamas?")' },
  { number: 29, description: 'responde a la pregunta: "¿Qué pasa si ... " (por ejemplo," ... se te cae un huevo :\')' },
  { number: 30, description: 'usa cinco o más contracciones (por ejemplo, al, del, verlo)' },
  { number: 31, description: 'utiliza expresiones faciales y lenguaje corporal para mostrar al menos cinco emociones (por ejemplo, "Muéstrame cómo te verías si estuvieras ... enfadado, orgulloso, asustado, asustado :\')' },
  { number: 32, description: 'hace afirmaciones sobre causa y efecto (por ejemplo, "No rueda porque la rueda está atascada:")' },
  { number: 33, description: 'define cinco palabras sencillas (por ejemplo, "¿Qué es un coche?")' },
  { number: 34, description: 'completa al menos tres analogías verbales simples (por ejemplo, "Papá es un hombre; Mamá es una ___ .")' },
  { number: 35, description: 'indica similitudes entre objetos para al menos tres pares de objetos (por ejemplo, "¿En qué se parecen los zapatos y las botas?")' },
  { number: 36, description: 'responde a "Dime lo contrario de ___ "durante al menos tres palabras' },
  { number: 37, description: 'Utiliza los plurales irregulares correctamente (por ejemplo, pie/pies, ganso/gansos)' },
  { number: 38, description: 'cuenta chistes sencillos' },
  { number: 39, description: 'establece diferencias entre objetos para al menos tres pares de objetos (por ejemplo, "¿En qué se diferencian la leche y el agua?")' },
  { number: 40, description: 'Utiliza "ayer" y "mañana" de forma significativa' },
  { number: 41, description: 'Utiliza correctamente comparativos irregulares (por ejemplo, bueno, mejor, el mejor)' },
];

export const DAYC2_SPANISH_DOMAINS: DAYC2Domain[] = [
  {
    id: 'socialemotional',
    name: 'Social Emotional',
    items: SOCIALEMOTIONAL_ITEMS,
    entryPoints: [{"label": "Birth-11 months", "startItem": 1}, {"label": "12-23 months", "startItem": 16}, {"label": "24-35 months", "startItem": 28}, {"label": "36-47 months", "startItem": 38}, {"label": "48-59 months", "startItem": 46}, {"label": "60+ months", "startItem": 51}],
  },
  {
    id: 'adaptivebahavior',
    name: 'Adaptive Behavior',
    items: ADAPTIVEBAHAVIOR_ITEMS,
    entryPoints: [{"label": "Birth-11 months", "startItem": 1}, {"label": "12-23 months", "startItem": 16}, {"label": "24-35 months", "startItem": 23}, {"label": "36-47 months", "startItem": 38}, {"label": "48-59 months", "startItem": 46}, {"label": "60+ months", "startItem": 51}],
  },
  {
    id: 'receptivecomm',
    name: 'Receptive Comm',
    items: RECEPTIVECOMM_ITEMS,
    entryPoints: [{"label": "Birth-11 months", "startItem": 1}, {"label": "12-23 months", "startItem": 11}, {"label": "24-35 months", "startItem": 16}, {"label": "36-47 months", "startItem": 22}, {"label": "48-59 months", "startItem": 28}, {"label": "60+ months", "startItem": 32}],
  },
  {
    id: 'expressivecomm',
    name: 'Expressive Comm',
    items: EXPRESSIVECOMM_ITEMS,
    entryPoints: [{"label": "Birth-11 months", "startItem": 1}, {"label": "12-23 months", "startItem": 11}, {"label": "24-35 months", "startItem": 16}, {"label": "36-47 months", "startItem": 24}, {"label": "48-59 months", "startItem": 30}, {"label": "60+ months", "startItem": 35}],
  },
];

export const DAYC2_SPANISH_AGE_RANGES = [
  { label: 'Birth-11 months', minMonths: 0, maxMonths: 11 },
  { label: '12-23 months', minMonths: 12, maxMonths: 23 },
  { label: '24-35 months', minMonths: 24, maxMonths: 35 },
  { label: '36-47 months', minMonths: 36, maxMonths: 47 },
  { label: '48-59 months', minMonths: 48, maxMonths: 59 },
  { label: '60+ months', minMonths: 60, maxMonths: 999 },
];

export function getDayc2SpanishStartItem(domainId: string, ageLabel: string): number {
  const domain = DAYC2_SPANISH_DOMAINS.find(d => d.id === domainId);
  if (!domain) return 1;
  const ep = domain.entryPoints.find(e => e.label === ageLabel);
  return ep ? ep.startItem : 1;
}

