// DAYC-2 Assessment Data
// Auto-generated from Excel template

export interface DAYC2Item {
  number: number;
  description: string;
}

export interface DAYC2Domain {
  id: string;
  name: string;
  items: DAYC2Item[];
  entryPoints: { label: string; startItem: number }[];
}

export const SOCIALEMOTIONAL_ITEMS: DAYC2Item[] = [
  { number: 1, description: 'relaxes body when held' },
  { number: 2, description: 'stops crying when talked to, picked up, or comforted' },
  { number: 3, description: 'establishes eye contact for at least a few seconds' },
  { number: 4, description: 'looks at adult face for several seconds looks at adult face for several seconds looks at adult face for several seconds' },
  { number: 5, description: 'smiles reflexively' },
  { number: 6, description: 'interacts by smiling and cooing' },
  { number: 7, description: 'recognizes familiar faces and objects (e.g., parent, bottle); reacts by waving arms and legs or squealing with excitement' },
  { number: 8, description: 'expresses feelings such as anger, tiredness, excitement, and hunger' },
  { number: 9, description: 'laughs, squeals, or shows enjoyment when caregiver involves child in play (e.g., moves hands to act out pat-a-cake, bounces on knee)' },
  { number: 10, description: 'comforts self (i.e., quits fussing by himself or herself)' },
  { number: 11, description: 'laughs when head is covered with cloth' },
  { number: 12, description: 'knows the difference between caregivers and strangers (e.g., smiles at loved ones; stares, quiets, or refuses to smile with stranger)' },
  { number: 13, description: 'smiles at or pats own image in the mirror' },
  { number: 14, description: 'when someone calls the child\'s name, he or she looks at the person and vocalizes' },
  { number: 15, description: 'extends arms to familiar persons' },
  { number: 16, description: 'shows preference for certain toys, activities, or places (e.g., interacts positively vs. negative response)' },
  { number: 17, description: 'expresses affection (e.g., hugging, patting, special looks, resting head)' },
  { number: 18, description: 'plays simple games (e.g., peek-a-boo, pat-a-cake)' },
  { number: 19, description: 'imitates facial expressions, actions, and sounds' },
  { number: 20, description: 'repeats activity that elicits laughter or positive response from others' },
  { number: 21, description: 'brings toys to share with caregiver' },
  { number: 22, description: 'plays well for brief time in groups of two or three children; at least some interaction among children' },
  { number: 23, description: 'spontaneously greets familiar person by hugging or other appropriate gesture' },
  { number: 24, description: 'separates from parent in familiar surroundings without crying' },
  { number: 25, description: 'attempts to comfort others in distress (e.g., comforts a child who is hurt or distressed)' },
  { number: 26, description: 'insists on trying to do many things without help (e.g., eating with spoon, putting on a coat)' },
  { number: 27, description: 'enjoys simple make-believe play (e.g., pretends he or she is the parent, is an animal, doll is a baby)' },
  { number: 28, description: 'shows pride in accomplishments' },
  { number: 29, description: 'quietly listens to story, music, movie, or TV' },
  { number: 30, description: 'sings familiar songs with adult' },
  { number: 31, description: 'uses "please" and "thank you" appropriately; may need to be reminded' },
  { number: 32, description: 'asks for assistance when having difficulty' },
  { number: 33, description: 'looks at person when speaking with him or her' },
  { number: 34, description: 'usually takes turns' },
  { number: 35, description: 'recognizes when another person is happy or sad' },
  { number: 36, description: 'avoids common dangers (e.g., sharp knives, fire, hot stove)' },
  { number: 37, description: 'plays dress-up' },
  { number: 38, description: 'shows off by repeating rhymes, songs, or dances for others' },
  { number: 39, description: 'changes from one activity to another when required by teacher or parent' },
  { number: 40, description: 'interacts appropriately with others during group games or activities' },
  { number: 41, description: 'knows and follows classroom rules' },
  { number: 42, description: 'gains attention from peers in appropriate ways' },
  { number: 43, description: 'plays group board or card games' },
  { number: 44, description: 'volunteers for tasks' },
  { number: 45, description: 'quiets down after active play' },
  { number: 46, description: 'likes competitive games' },
  { number: 47, description: 'returns objects to their appropriate place' },
  { number: 48, description: 'accepts mild, friendly teasing' },
  { number: 49, description: 'explains rules of a game to others' },
  { number: 50, description: 'expresses anger with nonaggressive words rather than with physical action' },
  { number: 51, description: 'offers item or activity to another in exchange for an item or activity' },
  { number: 52, description: 'accepts valid criticism without crying, pouting, or refusing to continue' },
  { number: 53, description: 'asks before using another\'s belongings' },
  { number: 54, description: 'provides or offers assistance to others when appropriate' },
  { number: 55, description: 'helps with group projects' },
  { number: 56, description: 'ends conversations with "good-bye" or other appropriate phrase' },
  { number: 57, description: 'apologizes if he or she hurts someone\'s feel ings' },
  { number: 58, description: 'remains calm when small requests are denied (e.g., cannot have a snack)' },
  { number: 59, description: 'works alone at chore for 20 to 30 minutes' },
  { number: 60, description: 'completes pencil/paper games (e.g., dot-to-dot, hidden pictures, mazes)' },
  { number: 61, description: 'initiates group activities' },
  { number: 62, description: 'congratulates others when appropriate' },
  { number: 63, description: 'answers the phone, remembers a simple message, and delivers it to the correct person' },
];

export const ADAPTIVEBAHAVIOR_ITEMS: DAYC2Item[] = [
  { number: 1, description: 'maintains body temperature without external assistance' },
  { number: 2, description: 'forms a tight seal around nipple when sucking' },
  { number: 3, description: 'swallows liquids with no difficulty' },
  { number: 4, description: 'coordinates sucking, swallowing, and breathing' },
  { number: 5, description: 'opens mouth in anticipation of feeding (sight of breast or bottle)' },
  { number: 6, description: 'enjoys bath; keeps eyes open and indicates pleasure when placed in warm water' },
  { number: 7, description: 'sleeps for 4- to 10-hour intervals' },
  { number: 8, description: 'closes lips when swallowing' },
  { number: 9, description: 'swallows pureed foods' },
  { number: 10, description: 'uses tongue to move food around in mouth' },
  { number: 11, description: 'shows definite likes and dislikes of various foods (e.g., may spit out or refuse to open lips for undesired foods, eagerly opens mouth for desired foods)' },
  { number: 12, description: 'sleeps through the night; may take two to three naps during the day' },
  { number: 13, description: 'holds or supports a bottle to feed self' },
  { number: 14, description: 'purposely pulls off own socks' },
  { number: 15, description: 'feeds self finger foods' },
  { number: 16, description: 'chews textured foods' },
  { number: 17, description: 'cooperates in dressing and undressing (e.g., helps put arms in holes)' },
  { number: 18, description: 'sleeps through the night; may take one nap during the day' },
  { number: 19, description: 'drinks from open cup or glass held by adult (not a sippy cup)' },
  { number: 20, description: 'sips liquid from glass or cup using a straw' },
  { number: 21, description: 'helps with simple household tasks (e.g., helps put things away)' },
  { number: 22, description: 'fusses when diaper needs to be changed' },
  { number: 23, description: 'tries to wash own hands and face' },
  { number: 24, description: 'removes loose clothing such as a jacket, shorts, or a shirt without assistance' },
  { number: 25, description: 'opens door by using handle or knob' },
  { number: 26, description: 'puts on simple clothing independently (e.g., hat, pants)' },
  { number: 27, description: 'independently eats entire meal with spoon' },
  { number: 28, description: 'wipes own nose; may need to be reminded' },
  { number: 29, description: 'sits on toilet for at least 1 minute supervised' },
  { number: 30, description: 'squats, holds self, or verbalizes bowel and bladder needs most of the time' },
  { number: 31, description: 'washes and dries hands and face without assistance' },
  { number: 32, description: 'cleans up spills, getting own cloth' },
  { number: 33, description: 'shows care when handling an infant or small animal' },
  { number: 34, description: 'pours milk or juice with some assistance' },
  { number: 35, description: 'tells adult of toilet needs in time to get to toilet' },
  { number: 36, description: 'takes responsibility for toileting; may require assistance in wiping' },
  { number: 37, description: 'gets drink of water from tap unassisted (may need help getting cup from cupboard)' },
  { number: 38, description: 'brushes teeth independently' },
  { number: 39, description: 'recognizes own home' },
  { number: 40, description: 'manipulates large buttons or snaps' },
  { number: 41, description: 'covers mouth and nose when coughing and sneezing (hand, elbow, tissue, or handkerchief may be used)' },
  { number: 42, description: 'sleeps through the night without wetting' },
  { number: 43, description: 'hangs up clothes (hanger, hook, or other designated device)' },
  { number: 44, description: 'dresses self completely, except for tying shoelaces (includes underwear; clothes must be on correctly, including all fasteners)' },
  { number: 45, description: 'serves self at the table (adult may need to hold serving dish)' },
  { number: 46, description: 'often wants privacy in bathroom' },
  { number: 47, description: 'answers what-to-do-if questions (e.g., "What would you do if you cut your finger?")' },
  { number: 48, description: 'fastens seat belt in automobile independently' },
  { number: 49, description: 'crosses street safely (e.g., looks both ways, uses crosswalks)' },
  { number: 50, description: 'puts dirty dishes in sink or dishwasher' },
  { number: 51, description: 'requests food to be passed at the table' },
  { number: 52, description: 'selects clothing appropriate for temperature and occasion' },
  { number: 53, description: 'makes own bed; may need to be reminded' },
  { number: 54, description: 'sets and clears table without assistance' },
  { number: 55, description: 'uses table knife for spreading soft butter, jelly, or peanut butter' },
  { number: 56, description: 'plans ahead to meet toileting needs before beginning an activity' },
  { number: 57, description: 'takes shower or bath independently' },
  { number: 58, description: 'cleans counter or work surface with sponge or paper towels' },
  { number: 59, description: 'dusts furniture' },
  { number: 60, description: 'makes simple breakfast and lunch' },
  { number: 61, description: 'washes own hair' },
  { number: 62, description: 'takes care of minor cuts (cleans and applies bandage)' },
  { number: 63, description: 'rides a bicycle safely without training wheels' },
  { number: 64, description: 'cuts food (including meat) into bite-sized pieces' },
];

export const RECEPTIVECOMM_ITEMS: DAYC2Item[] = [
  { number: 1, description: 'normal breathing rate' },
  { number: 2, description: 'reacts to loud noise by blinking, moving arms or legs, or stopping movement' },
  { number: 3, description: 'quieted by music' },
  { number: 4, description: 'turns head toward voice when someone speaks to him or her' },
  { number: 5, description: 'smiles at person who is talking or gesturing' },
  { number: 6, description: 'turns and looks toward noise' },
  { number: 7, description: 'briefly stops activity when name is called' },
  { number: 8, description: 'responds with appropriate gestures to "up;\' "bye-bye;\' or other routines' },
  { number: 9, description: 'moves body to music' },
  { number: 10, description: 'briefly stops activity when told "no"' },
  { number: 11, description: 'follows simple spoken commands (e.g., "Give Mommy the cup:\')' },
  { number: 12, description: 'responds to "where" questions (e.g., "Where is the ball?" May point, state the location, or go get the ball.)' },
  { number: 13, description: 'when asked, will point to five or more familiar persons, animals, or toys' },
  { number: 14, description: 'follows directions about placing one item "in" and "on" another' },
  { number: 15, description: 'indicates "yes" or "no" (or appropriate head movement) in response to questions' },
  { number: 16, description: 'points to three body parts when asked' },
  { number: 17, description: 'carries out two-step directions that are related (e.g., "Go to the table and bring me the toy:\')' },
  { number: 18, description: 'points to six body parts when asked' },
  { number: 19, description: 'points to 15 or more pictures of common objects when they are named' },
  { number: 20, description: 'understands at least three possessives (e.g., mine, yours, and boy\'s; "Is this your ball?" "Show me the dog\'s food:\')' },
  { number: 21, description: 'points to five or more common objects described by their use (e.g., "Show me what you eat with:\')' },
  { number: 22, description: 'carries out two-step unrelated commands (e.g., "Put the ball on the shelf and then clap your hands:\')' },
  { number: 23, description: 'understands negative (e.g., "Which is not ... red, the dog?")' },
  { number: 24, description: 'knows "big" and "little" (e.g., "Throw the big ball to me:\')' },
  { number: 25, description: 'responds to "who" and "whose" questions (e.g., "Who has on a red shirt today?")' },
  { number: 26, description: 'follows directions about placing one item "beside" and "under" another' },
  { number: 27, description: 'understands "in front of" and "behind" (e.g., "What is behind the screen?")' },
  { number: 28, description: 'answers comprehension questions when told a short story' },
  { number: 29, description: 'demonstrates understanding of passive sentences (e.g., "Show me the train was pushed by the car:\')' },
  { number: 30, description: 'carries out three-step commands that are not related (e.g., "Put the ball on the table, shut the door, and turn around:\')' },
  { number: 31, description: 'tells whether two words rhyme or have the same ending sound for at least three word pairs (e.g., "Do cat and pat have the same ending sound?")' },
  { number: 32, description: 'responds to questions involving time concepts (e.g., "When do we eat lunch?")' },
  { number: 33, description: 'understands all four seasons of the year and what you do in each (e.g., "What do we do in the summer?")' },
  { number: 34, description: 'can identify at least three opposites using pictures or objects ("Show me the opposite of ... big/little, hot/cold, tall/short:\')' },
  { number: 35, description: 'identifies "left" and "right" on own body (e.g., "Raise your right hand.")' },
  { number: 36, description: 'can identify at least three units of currency (e.g., "Point to the ... penny, dollar, quarter")' },
  { number: 37, description: 'can identify at least three complete sentences ("Tell me if this is a complete sentence:\' e.g., brown dog; The boy ran away.)' },
];

export const EXPRESSIVECOMM_ITEMS: DAYC2Item[] = [
  { number: 1, description: 'has a strong cry' },
  { number: 2, description: 'makes sucking noises' },
  { number: 3, description: 'cries when hungry or uncomfortable' },
  { number: 4, description: 'makes noises other than crying (e.g., cooing, gurgling)' },
  { number: 5, description: 'has different cries for pain, hunger, or discomfort' },
  { number: 6, description: 'produces three or more single vowel sounds (e.g., ah, eh, uh)' },
  { number: 7, description: 'laughs out loud' },
  { number: 8, description: 'produces three or more consonants, such as /b/, /m/, or /d/' },
  { number: 9, description: 'produces string of consonant-vowel sounds (e.g., ba-ba, da-da)' },
  { number: 10, description: 'uses word for parent or caregiver discriminately (e.g., mama, dada, nana)' },
  { number: 11, description: 'uses inflection patterns when vocalizing (e.g., raises pitch as if asking a question)' },
  { number: 12, description: 'spontaneously says familiar greetings and farewells' },
  { number: 13, description: 'has a word, sound, or sign for"drink"' },
  { number: 14, description: 'uses at least five words' },
  { number: 15, description: 'says one word that conveys entire thought; meaning depends on context (e.g., "cookie" may mean "wants more" or "the cookie fell")' },
  { number: 16, description: 'can name familiar characters or items seen on TV or in movies (e.g., Big Bird)' },
  { number: 17, description: 'knows names of two or more playmates' },
  { number: 18, description: 'uses 10 to 15 words spontaneously' },
  { number: 19, description: 'produces three or more two-word phrases (e.g., more juice)' },
  { number: 20, description: 'names eight or more pictures of familiar objects' },
  { number: 21, description: 'whispers' },
  { number: 22, description: 'uses sentences of three or more words' },
  { number: 23, description: 'uses at least 50 different words in spontaneous speech' },
  { number: 24, description: 'describes what he or she is doing (e.g., responds to "What are you doing?")' },
  { number: 25, description: 'asks "what" or "where" questions (e.g., "Where is my ball?")' },
  { number: 26, description: 'uses five or more regular plurals (e.g., boys, toys)' },
  { number: 27, description: 'changes speech depending on listener (e.g., talks differently to babies than to adults)' },
  { number: 28, description: 'gives full name on request (e.g., "What is your name?")' },
  { number: 29, description: 'answers question, "What happens if ... " (e.g.," ... you drop an egg:\')' },
  { number: 30, description: 'uses five or more contractions (e.g., I\'ll, can\'t)' },
  { number: 31, description: 'uses facial expressions and body language to demonstrate at least five emotions (e.g., "Show me how you would look if you were ... angry, proud, frightened, scared:\')' },
  { number: 32, description: 'makes statements about cause and effect (e.g., "It won\'t roll because the wheel is off:\')' },
  { number: 33, description: 'defines five simple words (e.g., "What is a car?")' },
  { number: 34, description: 'completes at least three simple verbal analogies (e.g., "Daddy is a man; Mommy is a ___ .")' },
  { number: 35, description: 'states similarities between objects for at least three object pairs (e.g., "How are shoes and boots alike?")' },
  { number: 36, description: 'responds to"Tell me the opposite of ___ "for at least three words' },
  { number: 37, description: 'uses irregular plurals correctly (e.g., foot/feet, goose/geese)' },
  { number: 38, description: 'tells simple jokes' },
  { number: 39, description: 'states differences between objects for at least three object pairs (e.g., "How are milk and water different?")' },
  { number: 40, description: 'uses "yesterday" and "tomorrow" meaningfully' },
  { number: 41, description: 'uses irregular comparatives correctly (e.g., good, better, best)' },
];

export const DAYC2_DOMAINS: DAYC2Domain[] = [
  {
    id: 'socialemotional',
    name: 'Social Emotional',
    items: SOCIALEMOTIONAL_ITEMS,
    entryPoints: [{"label": "Birth-11 months", "startItem": 1}, {"label": "12-23 months", "startItem": 16}, {"label": "24-35 months", "startItem": 28}, {"label": "36-47 months", "startItem": 38}, {"label": "48-59 months", "startItem": 46}, {"label": "60+ months", "startItem": 51}],
  },
  {
    id: 'adaptivebahavior',
    name: 'Adaptive Bahavior',
    items: ADAPTIVEBAHAVIOR_ITEMS,
    entryPoints: [{"label": "Birth-11 months", "startItem": 1}, {"label": "12-23 months", "startItem": 16}, {"label": "24-35 months", "startItem": 23}, {"label": "36-47 months", "startItem": 38}, {"label": "48-59 months", "startItem": 46}, {"label": "60+ months", "startItem": 51}],
  },
  {
    id: 'receptivecomm',
    name: 'Receptive Comm',
    items: RECEPTIVECOMM_ITEMS,
    entryPoints: [{"label": "Birth-11 months", "startItem": 1}, {"label": "12-23 months", "startItem": 11}, {"label": "24-35 months", "startItem": 16}, {"label": "36-47 months", "startItem": 22}, {"label": "48-59 months", "startItem": 28}, {"label": "60+ months", "startItem": 32}],
  },
  {
    id: 'expressivecomm',
    name: 'Expressive Comm',
    items: EXPRESSIVECOMM_ITEMS,
    entryPoints: [{"label": "Birth-11 months", "startItem": 1}, {"label": "12-23 months", "startItem": 11}, {"label": "24-35 months", "startItem": 16}, {"label": "36-47 months", "startItem": 24}, {"label": "48-59 months", "startItem": 30}, {"label": "60+ months", "startItem": 35}],
  },
];

export const DAYC2_AGE_RANGES = [
  { label: 'Birth-11 months', minMonths: 0, maxMonths: 11 },
  { label: '12-23 months', minMonths: 12, maxMonths: 23 },
  { label: '24-35 months', minMonths: 24, maxMonths: 35 },
  { label: '36-47 months', minMonths: 36, maxMonths: 47 },
  { label: '48-59 months', minMonths: 48, maxMonths: 59 },
  { label: '60+ months', minMonths: 60, maxMonths: 999 },
];

export function getDayc2StartItem(domainId: string, ageLabel: string): number {
  const domain = DAYC2_DOMAINS.find(d => d.id === domainId);
  if (!domain) return 1;
  const ep = domain.entryPoints.find(e => e.label === ageLabel);
  return ep ? ep.startItem : 1;
}

