// REEL-3 Assessment Data
// Auto-generated from Excel template

export interface REEL3Item {
  number: number;
  description: string;
}

export interface REEL3Domain {
  id: string;
  name: string;
  items: REEL3Item[];
  entryPoints: { label: string; startItem: number }[];
}

export const REEL3_RECEPTIVE_ITEMS: REEL3Item[] = [
  { number: 1, description: 'In response to an unexpected loud noise, does your baby suddenly blink her or his eyes, jerk back her or his whole body, and then, nearly as fast, return to normal appearance?' },
  { number: 2, description: 'Does your baby often stop moving for a while when she or he hears unusual sounds?' },
  { number: 3, description: 'When your baby is fussy, is she or he easily quieted by a familiar, friendly voice?' },
  { number: 4, description: 'When your baby hears new sounds or voices, does she or he often look toward those sounds?' },
  { number: 5, description: 'When your baby is wide awake and someone is talking, does.she or he often look toward those sounds?' },
  { number: 6, description: 'When someone is tallking, does your baby often look toward the speaker and smile?' },
  { number: 7, description: 'When someone is talking, does your baby often look directly at that speaker\'s face?' },
  { number: 8, description: 'Does your baby regularly shift.her or his eyes to look at whomever is speaking nearby, even if that person is not speaking to the baby?' },
  { number: 9, description: 'When someone is talking, does your baby often look at the mouth and lips of the speaker instead of at the speaker\'s whole face?' },
  { number: 10, description: 'Does your baby definitely turn both her or his head and eyes toward a nearby speaker?' },
  { number: 11, description: 'When your baby hears speakers she or he can\'t immediately see, does your baby seem to be looking about, trying to find the person who is speaking?' },
  { number: 12, description: 'When your baby hears an angry voice, does she or he become disturbed or frightened?' },
  { number: 13, description: 'Can your baby quickly find where a voice is truly coming from?' },
  { number: 14, description: 'Does your baby show signs of interest when she or he hears her or his own name spoken?' },
  { number: 15, description: 'Does your baby now usually stop crying when she or he hears a comforting, sympathetic voice talking to her or him?' },
  { number: 16, description: 'Do your baby\'s actions, gestures, or facial expressions show signs of reacting differently to warning, angry, and friendly voices?' },
  { number: 17, description: 'Does your baby show signs that she or he now knows what words like Daddy, Mama, or bye-bye mean?' },
  { number: 18, description: 'Does your baby, at least half of the time, stop or change direction when someone tells her or him "No!" or "Stop that!"?' },
  { number: 19, description: 'When you mention the name of a family member who isn\'t in the room with you, does your baby react to show that she or he knows who you\'re talking about?' },
  { number: 20, description: 'When you say words like Up! or Bye-bye!, does your baby lift her or his arms or wave in answer?' },
  { number: 21, description: 'When she or he hears music or singing, does your baby sometimes listen with interest?' },
  { number: 22, description: 'Does your baby often stop whatever she or he is doing and seem to listen to conversations between people?' },
  { number: 23, description: 'If your baby is moving or playing, does she or he regularly stop if someone calls her or his name?' },
  { number: 24, description: 'When you say the name of a familiar object, does your baby often look in the direction of that object as you are speaking to her or him?' },
  { number: 25, description: 'Does your baby respond to simple commands or requests like "Come here!" or "Let\'s go!"?' },
  { number: 26, description: 'Almost every time you say, "No!" or "Stop that!", does your baby stop at least temporarily?' },
  { number: 27, description: 'Will your baby sit still and listen for a full minute to a person who is showing and naming pictures of familiar things?' },
  { number: 28, description: 'Does your baby enjoy hearing words that name familiar objects?' },
  { number: 29, description: 'When someone is talking, can your baby usually listen without being distracted by other sounds or competing noises?' },
  { number: 30, description: 'When people ask your baby to give them toys or other things, will she or he usually do it?' },
  { number: 31, description: 'Does your baby sometimes obey when you give a simple order such as "Put that downt" or "Come here!"?' },
  { number: 32, description: 'When someone asks simple "where" questions, such as, "Where is Daddy?" or "Where is the ball?", does your baby act as if she or he understands what was asked?' },
  { number: 33, description: 'When your baby hears music with a beat, does she or he try to move to the music\'s beat?' },
  { number: 34, description: 'When someone asks your toddler to do simple things like "Give me five!" or "Show me your nose!". does your toddler do it?' },
  { number: 35, description: 'When someone talks to your toddler, even for a long time, does your toddler listen and seem interested?' },
  { number: 36, description: 'When someone asks your toddler to say words we associate with social routines, such as. "Say \'Bye-bye\'!" or "Can you say \'Hi\' to Grandpa?". does your toddler comply?' },
  { number: 37, description: 'Does your toddler appear to understand new words each week?' },
  { number: 38, description: 'Can you tell that your toddler usually recognizes the moods of most speakers? Examples: sad versus happy, serious versus humorous.' },
  { number: 39, description: 'Does your toddler point to many different objects, or pictures of objects , when someone names them?' },
  { number: 40, description: 'Does your toddler carry out a two-step request, like "Please go to your room and bring back a diaper," or "Pick up your ball and give it to me"?' },
  { number: 41, description: 'When you announce familiar routines such as "Snack time!" or "Bath time!", does your toddler seem to anticipate what is going to happen?' },
  { number: 42, description: 'When someone names major,body parts such as hands, legs, feet, and nose, does your toddler point to these on her or his own body?' },
  { number: 43, description: 'If you talk to your toddler about a toy.that is in another room, does she or he know what you mean?' },
  { number: 44, description: 'When someone,asks your toddler to name things such as animals, toys, or things to wear, does she or he tell you specific examples?' },
  { number: 45, description: 'Does your toddler enjoy listening to nursery rhymes, finger plays, or songs?' },
  { number: 46, description: 'Does your toddler pause during conversation and wait for the other person to comment on what she or he has just said?' },
  { number: 47, description: 'When someone tells your toddler to do things, using action words such as jump, throw, run, or swing, and without using gestures, does she or he perform the actions?' },
  { number: 48, description: 'Does your toddler follow such commands as "Give it to her," "Let him have it," or "Show it to them"?' },
  { number: 49, description: 'When someone gives your child a three-part command. does she or he complete all three tasks? For example, "Please go to your room and get your shoes and bring them to me."' },
  { number: 50, description: 'Do you notice that every day your child seems to recognize the meanings of more and more new words?' },
  { number: 51, description: 'Does your child understand the meaning of most objects and actions you talk about or show her or him in pictures?' },
  { number: 52, description: 'When asked to pick out one object from a group of five different objects, such as a ball, a book, a crayon, a teddy bear, and a penny, does your child pick the right one?' },
  { number: 53, description: 'When people talk to your child using longer sentences, does your child understand the meaning of the whole sentence rather than just a few key words?' },
  { number: 54, description: 'When your child hears a complex sentence, does she or he remember what it means? Examples: "When we get to the store, l\'ll buy you an ice cream cone," or "Do you want to go for a walk and then play on the swings in the park?"' },
  { number: 55, description: 'While sharing books or magazines, can your child point to pictures involving five simple actions when you ask questions like "Who is eating?" or "Can you show me someone who is swinging?"' },
  { number: 56, description: 'Does your child point to smaller body parts when asked? For example, her or his chin, eyebrow, belly button, toe?' },
  { number: 57, description: 'Can your child answer "yes" or "no" to questions about playmates or family members when you mention them by the names of their relationships? For example, "does Charlie have any brothers or sisters?" or "Did you meet Latoya\'s mother (or grandmother or aunt)? "' },
  { number: 58, description: 'Can your child give specific examples in answer to questions that require her or him to know what things are called or how they go together? For example, when you ask, "What do you want to eat for lunch?" or "Which toy do you want me to get?", does she or he give a specific answer?' },
  { number: 59, description: 'Does your child understand questions or requests for things that differ in size or in color? For example, "Which doll is the biggest?" or "Let\'s get the red ball."' },
  { number: 60, description: 'Does your child understand about events that have happened in the past or will happen in the future? For example, when you say, "We went there yesterday" or "We\'ll be going to the circus tomorrow."' },
  { number: 61, description: 'Can your child usually follow two requests that are not directly related to each other? For example, "Please take off your jacket and then find that puppy!"' },
  { number: 62, description: 'When adults talk with your child in normal adult language rather than in baby talk, does your child generally understand what they are talking about?' },
  { number: 63, description: 'Does your child understand most words that describe objects or people? For example, the fat dog, the spotted kitten, or a rough board.' },
  { number: 64, description: 'Does your child listen to explanations of why and how things work? For example, "The clothes go around in the dryer, and then the heat takes out the water" or "We have to put moneyin the machine to get a soda."' },
  { number: 65, description: 'Does your child understapd position words? For example, when you talk about an object or person being "behind the door," or "on top of the table"?' },
  { number: 66, description: 'Does your child remember the events and sequences of favorite stories so that she or he is able to anticipate what will happen next?' },
];

export const REEL3_EXPRESSIVE_ITEMS: REEL3Item[] = [
  { number: 1, description: 'Does your baby cry a lot and in a loud, clear voice?' },
  { number: 2, description: 'Besides crying, does your baby make different kinds of sounds?' },
  { number: 3, description: 'When your baby cries or makes sounds, do they sound mostly like any of these: "A-A-A" as in ate (or eight), or "E-E-E" as in eat, or "A-A-A" as in at?' },
  { number: 4, description: 'Can you tell when your baby is hungry just by the way she or he cries?' },
  { number: 5, description: 'Does your baby make sounds showing contentment while someone is feeding her or him, or after feeding?' },
  { number: 6, description: 'Can you tell that your baby is happy just by the sounds she or he makes?' },
  { number: 7, description: 'When hearing voices, does your baby ever vocalize back?' },
  { number: 8, description: 'When someone plays with your baby, such as tickling, does she or he laugh and make other happy sounds?' },
  { number: 9, description: 'Does your baby seem to make more sounds when she or he is face-to-face with people who are caring for her or him than when she or he is alone?' },
  { number: 10, description: 'Does your baby make new sounds, such as "o-o-o" as in cool or glue?' },
  { number: 11, description: 'Do your baby\'s sounds vary from loud to soft and from high to low?' },
  { number: 12, description: 'Does your baby make sounds such as "pah," "bah," or "mah"?' },
  { number: 13, description: 'When your baby plays with toys or objects, does she or he often laugh or chatter?' },
  { number: 14, description: 'Does your baby let you know that she or he is unhappy or angry by making sounds other than crying?' },
  { number: 15, description: 'Does your baby sometimes make the same sound over and over again, such as "aaa-aaa" (the first sound in at) or "eee-eee" (the first sound ih eat)?' },
  { number: 16, description: 'When your baby sees or senses someone, does she or he start babbling or chatting directly to that other person?' },
  { number: 17, description: 'Does your baby make combinations of sounds such as "pa-dah," "tah-koo," "oo-bah," or "bah-dah"?' },
  { number: 18, description: 'Does your baby playfully babble or chatter?' },
  { number: 19, description: 'When your baby wakes up or when you are busy, does your baby not cry but rather shout to get your attention?' },
  { number: 20, description: 'When you call your baby by name, will she or he sometimes reply vocally?' },
  { number: 21, description: 'Does your baby use word-like expressions so that she or he appears to be naming some things in her or his own language?' },
  { number: 22, description: 'Does your baby make sounds while her or his body is still?' },
  { number: 23, description: 'Does your baby sometimes play games such as "pat-a-cake" or "peekaboo"?' },
  { number: 24, description: 'Does your baby sometimes use her or his own words or sounds to sing along with familiar songs?' },
  { number: 25, description: 'Does your baby try to imitate what she or he hears from you or from people nearby?' },
  { number: 26, description: 'Even if your baby doesn\'t use real words. does she or he sometimes seem to talk in complete sentences or phrases?' },
  { number: 27, description: 'When your baby makes "ooh" and "aah" sounds, do they sometimes start with other sounds like "t-ah," "n-ah," "p-ah," and "k-ah"?' },
  { number: 28, description: 'Does your baby use the same word forms consistently so that you recognize that she or he associates them with certain situations, such as when she or he wants water or a toy?' },
  { number: 29, description: 'Does your baby use exclamations such as "Uh-Oh!" or "Unh-Unh"?' },
  { number: 30, description: 'Does your baby use words to tell you when she or he wants or doesn\'t want something, such as "No!" when she or he doesn\'t want a particular food?' },
  { number: 31, description: 'Does your baby sometimes start games such as "pat-a-cake" or "peekaboo"?' },
  { number: 32, description: 'When your baby vocalizes, do most of her or his expressions sound more contented or happy than angry or frustrated?' },
  { number: 33, description: 'When your baby wants you to get something or to do something, does she or he not whine and cry, but gesture and use a firm voice?' },
  { number: 34, description: 'Besides Mama or Dada, does your toddler say some words in the same way each time, so that most people who hear her or him understand what those words mean?' },
  { number: 35, description: 'Does your toddler jabber sometimes for a long time, talking to toys and people throughout the day?' },
  { number: 36, description: 'Does your toddler frequently respond to songs or rhymes by vocalizing or trying to sing along or talk?' },
  { number: 37, description: 'Can you tell from the way your toddler\'s voice sounds that she or he is asking a question?' },
  { number: 38, description: 'Does your toddler combine words with gestures to let you know what she or he wants or wants you to do?' },
  { number: 39, description: 'Do you sometimes hear real words while your toddler is talking?' },
  { number: 40, description: 'Does your toddler greet and say good-bye to people with words such as hi and bye-bye, or with her or his own version of them?' },
  { number: 41, description: 'Sometimes you aren\'t paying attention to an object, pet, toy, or person that your toddler wants you to notice. Does she or he ever comment to get you to pay attention to it?' },
  { number: 42, description: 'When your toddler talks with someone, does she or he often use real words along with motions or gestures?' },
  { number: 43, description: 'Do you notice your toddler often repeating or imitating words heard in conversation?' },
  { number: 44, description: 'Does your toddler label or have names for all her or his favorite toys, foods, pets, or other objects?' },
  { number: 45, description: 'Does your toddler repeat or practice certain words she or he seems to like?' },
  { number: 46, description: 'Does your toddler imitate sounds around her or him during play, such as the sounds of cars or animals?' },
  { number: 47, description: 'Do you believe that your toddler says about 50 words?' },
  { number: 48, description: 'Have you heard your toddler use any two­ word sentences or phrases, such as "Throw ball" or "Daddy gone?"' },
  { number: 49, description: 'Does your child say at least two new words each week?' },
  { number: 50, description: 'Does your child try to tell you what has happened to her or him, using some real words?' },
  { number: 51, description: 'Do you hear your child use words such as I, it, or my in her or his conversations?' },
  { number: 52, description: 'Does your child refer to herself or himself by using her or his own name?' },
  { number: 53, description: 'When your child can\'t make people under­ stand what she or he is saying, does she or he show signs of frustration?' },
  { number: 54, description: 'Does your child use words ending in -ing, as in making?' },
  { number: 55, description: 'When your child says words that have definite beginning and ending sounds, does she or he pronounce both the beginning and ending sounds? Examples: both the /k/ and the /ti sounds in cat, or both the /j/ and the /s/ in juice' },
  { number: 56, description: 'Does your child tell you that she or he needs help with personal needs such as getting a drink, washing hands, or going to the toilet?' },
  { number: 57, description: 'Does your child tell you where something might be, using words such as in, on, orby?' },
  { number: 58, description: 'Does your child generally refer to more than one thing by adding ans as in dogs or cats?' },
  { number: 59, description: 'Does your child sometimes use complicated sentences, such as "I hope that this bear is mine"?' },
  { number: 60, description: 'Does your child answer what, where, when, and who questions with more than just a "yes" or "no"?' },
  { number: 61, description: 'Does your child use words that tell about color and size?' },
  { number: 62, description: 'Do most people understand what your child is saying most of the time?' },
  { number: 63, description: 'Does your child use different voice tones and words such as please when speaking to people of different status, such as talking with another child versus talking with a grandparent?' },
  { number: 64, description: 'Can your child retell familiar stories from books, TV, and movies, or make up stories?' },
  { number: 65, description: 'Does your child ask questions that begin with What, When, or Where?' },
  { number: 66, description: 'Does your child maintain a topic of conversa­ tion by taking turns and commenting appro­ priately on what the other person says?' },
];

export const REEL3_DOMAINS: REEL3Domain[] = [
  {
    id: 'receptive',
    name: 'Receptive',
    items: REEL3_RECEPTIVE_ITEMS,
    entryPoints: [{"label": "Birth-6 months", "startItem": 1}, {"label": "7-12 months", "startItem": 16}, {"label": "13-18 months", "startItem": 34}, {"label": "19-24 months", "startItem": 43}, {"label": "25-36 months", "startItem": 49}],
  },
  {
    id: 'expressive',
    name: 'Expressive',
    items: REEL3_EXPRESSIVE_ITEMS,
    entryPoints: [{"label": "Birth-6 months", "startItem": 1}, {"label": "7-12 months", "startItem": 16}, {"label": "13-18 months", "startItem": 34}, {"label": "19-24 months", "startItem": 43}, {"label": "25-36 months", "startItem": 49}],
  },
];

export const REEL3_AGE_RANGES = [
  { label: 'Birth-6 months', minMonths: 0, maxMonths: 6 },
  { label: '7-12 months', minMonths: 7, maxMonths: 12 },
  { label: '13-18 months', minMonths: 13, maxMonths: 18 },
  { label: '19-24 months', minMonths: 19, maxMonths: 24 },
  { label: '25-36 months', minMonths: 25, maxMonths: 36 },
];

// Age Equivalent Table (Table D.1)
export const REEL3_AGE_EQUIVALENT: { raw: number; receptiveMonths: number | null; expressiveMonths: number | null }[] = [
  { raw: 0, receptiveMonths: null, expressiveMonths: null },
  { raw: 1, receptiveMonths: 11, expressiveMonths: 9 },
  { raw: 2, receptiveMonths: 12, expressiveMonths: 11 },
  { raw: 3, receptiveMonths: 14, expressiveMonths: 13 },
  { raw: 4, receptiveMonths: 16, expressiveMonths: 15 },
  { raw: 5, receptiveMonths: 18, expressiveMonths: 17 },
  { raw: 6, receptiveMonths: 20, expressiveMonths: 19 },
  { raw: 7, receptiveMonths: 23, expressiveMonths: 22 },
  { raw: 8, receptiveMonths: 26, expressiveMonths: 25 },
  { raw: 9, receptiveMonths: 29, expressiveMonths: 28 },
  { raw: 10, receptiveMonths: 32, expressiveMonths: 31 },
  { raw: 11, receptiveMonths: 35, expressiveMonths: 34 },
  { raw: 12, receptiveMonths: 38, expressiveMonths: 37 },
  { raw: 13, receptiveMonths: 41, expressiveMonths: 40 },
  { raw: 14, receptiveMonths: 43, expressiveMonths: 41 },
  { raw: 15, receptiveMonths: 44, expressiveMonths: 42 },
  { raw: 16, receptiveMonths: 46, expressiveMonths: 43 },
  { raw: 17, receptiveMonths: 47, expressiveMonths: 44 },
  { raw: 18, receptiveMonths: 48, expressiveMonths: 46 },
  { raw: 19, receptiveMonths: 49, expressiveMonths: 47 },
  { raw: 20, receptiveMonths: 51, expressiveMonths: 48 },
  { raw: 21, receptiveMonths: 52, expressiveMonths: 50 },
  { raw: 22, receptiveMonths: 53, expressiveMonths: 52 },
  { raw: 23, receptiveMonths: null, expressiveMonths: 53 },
  { raw: 24, receptiveMonths: 54, expressiveMonths: 54 },
  { raw: 25, receptiveMonths: null, expressiveMonths: 56 },
  { raw: 26, receptiveMonths: 55, expressiveMonths: 57 },
  { raw: 27, receptiveMonths: 56, expressiveMonths: null },
  { raw: 28, receptiveMonths: null, expressiveMonths: 58 },
  { raw: 29, receptiveMonths: 57, expressiveMonths: null },
  { raw: 30, receptiveMonths: 58, expressiveMonths: 59 },
  { raw: 31, receptiveMonths: null, expressiveMonths: 60 },
  { raw: 32, receptiveMonths: 59, expressiveMonths: 61 },
  { raw: 33, receptiveMonths: 60, expressiveMonths: 62 },
  { raw: 34, receptiveMonths: 61, expressiveMonths: 63 },
  { raw: 35, receptiveMonths: 63, expressiveMonths: 65 },
  { raw: 36, receptiveMonths: 65, expressiveMonths: 66 },
];

// Ability to Percentile Rank
export const REEL3_ABILITY_TO_PERCENTILE: { ability: number; percentile: number }[] = [
  { ability: 0, percentile: 0.5 },
  { ability: 65, percentile: 1 },
  { ability: 69, percentile: 2 },
  { ability: 71, percentile: 3 },
  { ability: 74, percentile: 4 },
  { ability: 75, percentile: 5 },
  { ability: 77, percentile: 6 },
  { ability: 78, percentile: 7 },
  { ability: 79, percentile: 8 },
  { ability: 80, percentile: 9 },
  { ability: 81, percentile: 10 },
  { ability: 82, percentile: 12 },
  { ability: 83, percentile: 13 },
  { ability: 84, percentile: 14 },
  { ability: 85, percentile: 16 },
  { ability: 86, percentile: 18 },
  { ability: 87, percentile: 19 },
  { ability: 88, percentile: 21 },
  { ability: 89, percentile: 23 },
  { ability: 90, percentile: 25 },
  { ability: 91, percentile: 27 },
  { ability: 82, percentile: 30 },
  { ability: 93, percentile: 32 },
  { ability: 94, percentile: 35 },
  { ability: 95, percentile: 37 },
  { ability: 96, percentile: 39 },
  { ability: 97, percentile: 42 },
  { ability: 98, percentile: 45 },
  { ability: 99, percentile: 47 },
  { ability: 100, percentile: 50 },
  { ability: 101, percentile: 53 },
  { ability: 102, percentile: 55 },
  { ability: 103, percentile: 58 },
  { ability: 104, percentile: 61 },
  { ability: 105, percentile: 63 },
  { ability: 106, percentile: 65 },
  { ability: 107, percentile: 68 },
  { ability: 108, percentile: 70 },
  { ability: 109, percentile: 73 },
  { ability: 110, percentile: 75 },
  { ability: 111, percentile: 77 },
  { ability: 112, percentile: 79 },
  { ability: 113, percentile: 81 },
  { ability: 114, percentile: 82 },
  { ability: 115, percentile: 84 },
  { ability: 116, percentile: 86 },
  { ability: 117, percentile: 87 },
  { ability: 118, percentile: 89 },
  { ability: 119, percentile: 90 },
  { ability: 120, percentile: 91 },
  { ability: 121, percentile: 92 },
  { ability: 122, percentile: 93 },
  { ability: 123, percentile: 94 },
  { ability: 124, percentile: 95 },
  { ability: 126, percentile: 96 },
  { ability: 127, percentile: 97 },
  { ability: 130, percentile: 98 },
  { ability: 132, percentile: 99 },
  { ability: 136, percentile: 99.5 },
];

// Descriptive Terms
export const REEL3_DESCRIPTIVE_TERMS: { ability: number; term: string }[] = [
  { ability: 0, term: 'Very Poor' },
  { ability: 70, term: 'Poor' },
  { ability: 80, term: 'Below Average' },
  { ability: 90, term: 'Average' },
  { ability: 111, term: 'Above Average' },
  { ability: 121, term: 'Superior' },
  { ability: 131, term: 'Very Superior' },
];

// Language Ability (Table B)
export const REEL3_LANGUAGE_ABILITY: { subtestSum: number; languageAbility: number }[] = [
  { subtestSum: 90, languageAbility: 34 },
  { subtestSum: 91, languageAbility: 35 },
  { subtestSum: 93, languageAbility: 36 },
  { subtestSum: 95, languageAbility: 37 },
  { subtestSum: 96, languageAbility: 38 },
  { subtestSum: 98, languageAbility: 39 },
  { subtestSum: 100, languageAbility: 40 },
  { subtestSum: 101, languageAbility: 41 },
  { subtestSum: 103, languageAbility: 42 },
  { subtestSum: 105, languageAbility: 43 },
  { subtestSum: 106, languageAbility: 44 },
  { subtestSum: 108, languageAbility: 45 },
  { subtestSum: 111, languageAbility: 46 },
  { subtestSum: 113, languageAbility: 47 },
  { subtestSum: 115, languageAbility: 48 },
  { subtestSum: 116, languageAbility: 49 },
  { subtestSum: 117, languageAbility: 50 },
  { subtestSum: 118, languageAbility: 51 },
  { subtestSum: 120, languageAbility: 52 },
  { subtestSum: 121, languageAbility: 53 },
  { subtestSum: 123, languageAbility: 54 },
  { subtestSum: 125, languageAbility: 55 },
  { subtestSum: 126, languageAbility: 56 },
  { subtestSum: 128, languageAbility: 57 },
  { subtestSum: 130, languageAbility: 58 },
  { subtestSum: 131, languageAbility: 59 },
  { subtestSum: 133, languageAbility: 60 },
  { subtestSum: 135, languageAbility: 61 },
  { subtestSum: 136, languageAbility: 62 },
  { subtestSum: 138, languageAbility: 63 },
  { subtestSum: 140, languageAbility: 64 },
  { subtestSum: 141, languageAbility: 65 },
  { subtestSum: 143, languageAbility: 66 },
  { subtestSum: 145, languageAbility: 67 },
  { subtestSum: 146, languageAbility: 68 },
  { subtestSum: 148, languageAbility: 69 },
  { subtestSum: 150, languageAbility: 70 },
  { subtestSum: 151, languageAbility: 71 },
  { subtestSum: 153, languageAbility: 72 },
  { subtestSum: 155, languageAbility: 73 },
  { subtestSum: 156, languageAbility: 74 },
  { subtestSum: 158, languageAbility: 75 },
  { subtestSum: 160, languageAbility: 76 },
  { subtestSum: 161, languageAbility: 77 },
  { subtestSum: 163, languageAbility: 78 },
  { subtestSum: 165, languageAbility: 79 },
  { subtestSum: 166, languageAbility: 80 },
  { subtestSum: 168, languageAbility: 81 },
  { subtestSum: 170, languageAbility: 82 },
  { subtestSum: 171, languageAbility: 83 },
  { subtestSum: 173, languageAbility: 84 },
  { subtestSum: 175, languageAbility: 85 },
  { subtestSum: 176, languageAbility: 86 },
  { subtestSum: 178, languageAbility: 87 },
  { subtestSum: 180, languageAbility: 88 },
  { subtestSum: 181, languageAbility: 89 },
  { subtestSum: 183, languageAbility: 90 },
  { subtestSum: 185, languageAbility: 91 },
  { subtestSum: 186, languageAbility: 92 },
  { subtestSum: 188, languageAbility: 93 },
  { subtestSum: 190, languageAbility: 94 },
  { subtestSum: 191, languageAbility: 95 },
  { subtestSum: 193, languageAbility: 96 },
  { subtestSum: 195, languageAbility: 97 },
  { subtestSum: 196, languageAbility: 98 },
  { subtestSum: 198, languageAbility: 99 },
  { subtestSum: 200, languageAbility: 100 },
  { subtestSum: 201, languageAbility: 101 },
  { subtestSum: 203, languageAbility: 102 },
  { subtestSum: 205, languageAbility: 103 },
  { subtestSum: 206, languageAbility: 104 },
  { subtestSum: 208, languageAbility: 105 },
  { subtestSum: 210, languageAbility: 106 },
  { subtestSum: 211, languageAbility: 107 },
  { subtestSum: 213, languageAbility: 108 },
  { subtestSum: 215, languageAbility: 109 },
  { subtestSum: 216, languageAbility: 110 },
  { subtestSum: 218, languageAbility: 111 },
  { subtestSum: 220, languageAbility: 112 },
  { subtestSum: 221, languageAbility: 113 },
  { subtestSum: 223, languageAbility: 114 },
  { subtestSum: 225, languageAbility: 115 },
  { subtestSum: 226, languageAbility: 116 },
  { subtestSum: 228, languageAbility: 117 },
  { subtestSum: 230, languageAbility: 118 },
  { subtestSum: 231, languageAbility: 119 },
  { subtestSum: 233, languageAbility: 120 },
  { subtestSum: 235, languageAbility: 121 },
  { subtestSum: 236, languageAbility: 122 },
  { subtestSum: 238, languageAbility: 123 },
  { subtestSum: 240, languageAbility: 124 },
  { subtestSum: 241, languageAbility: 125 },
  { subtestSum: 243, languageAbility: 126 },
  { subtestSum: 245, languageAbility: 127 },
  { subtestSum: 246, languageAbility: 128 },
  { subtestSum: 248, languageAbility: 129 },
  { subtestSum: 250, languageAbility: 130 },
  { subtestSum: 251, languageAbility: 131 },
  { subtestSum: 253, languageAbility: 132 },
  { subtestSum: 255, languageAbility: 133 },
  { subtestSum: 256, languageAbility: 134 },
  { subtestSum: 258, languageAbility: 135 },
  { subtestSum: 260, languageAbility: 136 },
  { subtestSum: 261, languageAbility: 137 },
  { subtestSum: 263, languageAbility: 138 },
  { subtestSum: 265, languageAbility: 139 },
  { subtestSum: 266, languageAbility: 140 },
  { subtestSum: 268, languageAbility: 141 },
  { subtestSum: 270, languageAbility: 142 },
  { subtestSum: 271, languageAbility: 143 },
  { subtestSum: 273, languageAbility: 144 },
  { subtestSum: 275, languageAbility: 145 },
  { subtestSum: 276, languageAbility: 146 },
  { subtestSum: 278, languageAbility: 147 },
  { subtestSum: 280, languageAbility: 148 },
  { subtestSum: 281, languageAbility: 149 },
  { subtestSum: 283, languageAbility: 150 },
  { subtestSum: 285, languageAbility: 151 },
  { subtestSum: 286, languageAbility: 152 },
  { subtestSum: 288, languageAbility: 153 },
  { subtestSum: 290, languageAbility: 154 },
  { subtestSum: 291, languageAbility: 155 },
];

export function getReel3StartItem(_domainId: string, ageLabel: string): number {
  const domain = REEL3_DOMAINS[0]; // Same entry points for both domains
  const ep = domain.entryPoints.find(e => e.label === ageLabel);
  return ep ? ep.startItem : 1;
}

